### ISSUE TITLE
Migration system/s

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#11]
Migration was an important aspect during this time period. Especially for the Celts.
So I thought about a few options and their issues.
## Rebels

Desc: Creating a rebel type which demand money on success
Issue: Using the rebel system doesn't seem quite right
## Giving CB's to the migrators

Desc: Giving them CB's or direct decisions to start a war
Issue: Goal country might be too far away and can't be reached due to no military access from other countries
## Creating a "Migrators" country

Desc: Creating a country much like Jan Mayen that starts a war by event with the goal country and gets troops spawned on an adjacent province (if that's possible)
Issue: Not sure if it's even possible to do and a lot of work

**Comment by qweytr** [comment]
I think the Celts should be able to migrate using the Native American mechanics. I also don't think that they need any additional CBs. There are already ones in vanilla that give a CB for all tribal nations against other tribal nations. This would of course mean that there would have to be some uncolonized provinces to migrate to.

**Comment by Firesoul7** [comment]
My concern with using native american mechanics is how close together
celtic nations lived. I think we need an improved system.

**Comment by PhelanBavaria** [comment]
sorry, I forgot to mention that I'm referring to historical events, such as the invasion of Greece.
I don't think that the Native American mechanics would work.

**Comment by qweytr** [comment]
When did the Celts invade Greece?

**Comment by Firesoul7** [comment]
279 BC, I hadn't heard of it before Bavarian talked about it either. 

Sent from my Samsung device

-------- Original message --------

**Comment by qweytr** [comment]
Those weren't really migrations, as the Celts never stayed there. They were just military invasions that they are already perfectly capable of doing. If needed, that kind of behavior can be encouraged with missions and/or unique CBs, but I don't think that any new mechanics are needed.

**Comment by PhelanBavaria** [comment]
Yes they were real migrations. They were defeated and some went on to form the kingdom of Tylis and others to form Galatia.
the issue with military invasions is, will they be able to pass through all of the Illyrian tribes?
Also, how do we go about forming Tylis and Galatia? Rebels seem the best solution in this case in my opinion.

**Comment by Firesoul7** [comment]
The problem is with rebels is that a Greek province would never defect to a
Celtic nation.

**Comment by qweytr** [comment]
It would be possible to make a custom rebel type that can defect to certain countries regardless of the culture. I think there should be a way for Tylis and Galatia to appear, but there are plenty of other countries as well that should be possible to appear, so the mechanic should not be made specific to Celts. 

The AI usually tries to get military access, if they are at war with a country they can't reach otherwise. They might not always be able to get the access though, as they could have too low relations with some countries on the way. This could be fixed by either giving the migrating countries relation bonuses with some neighboring countries or by making the migrations just happen more often. That way they would be able to reach the target often enough even if they fail to do so sometimes.

**Comment by PhelanBavaria** [comment]
Yes, but I would rather use rebels than just giving them provinces by event, because if you play a nation that owns those provinces, at least you should be given a fair fight.
I guess we should make a rebel type for everybody who appeared that way on the worldmap.
I don't like them declaring war but having to sign a white peace, just because they couldn't travel through a country. Would it be possible somehow to let them occupy a province of the enemy and make them spawn troops there?

**Comment by qweytr** [comment]
I agree with not having events that change province ownership. Another way to represent the migrations and the one I use in ET to represent the Slavic migrations to the Balkans is to have an event that changes the culture and religion of some provinces and adds cores for the target nation there allowing it to then gain independence through normal rebels. 

I think that finding your way to the target is an important part of the migrations and rebels just appearing there out of nowhere wouldn't represent that very well. The military invasions are in my opinion the way to go. The chances for military access failures can be minimized with careful triggers for the target countries.

**Comment by PhelanBavaria** [comment]
Hum, you might be right, but I don't think that changing culture and giving them a core would be so good, because then you have to reconvert the province.
Also, both Tylis and Galatia were a Celtic ruling class, the people were still what they used to be, only ruled by Celts.
I guess we can find a good way with letting them invade by CB and on certain requirements, rebels in the region of Tylis spawn, and Galatia is just given land (since that was how it actually happened).
