### ISSUE TITLE
Tribes "popping in"

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#13]
We can't have all tribes exist since the beginning of time, and I'm not quite sure when to let them start existing.
So there are two issues:
What makes a tribe no longer be a uncolonized province, and instead an actual nation?
When should they start to pop in?
My first idea was to let them appear when they become relevant, so only a hand full of Gallic tribes will exist from about 600 BC (Arverni, Aedui and some others), while the rest of the tribe starts to pop in before Caesars invasion.
What do you guys think?

**Comment by yugoslavia45** [comment]
I agree same thing with Illyria Most tribes lived in genral obbsucurity until a certain year then they popped into revelance

**Comment by PanzerfaustJoe** [comment]
I agree that more tribes or even countries should pop up as the years pass by, essentially filling out the uncolonized land.

**Comment by Firesoul7** [comment]
I don't like the idea that Caesar's invasion causes a massive number of tribes to appear from nowhere. I think it should be much more spread out. 

Sent from my Samsung device

-------- Original message --------

**Comment by qweytr** [comment]
The date the tribe is first mentioned in historical sources is usually the most logical.

**Comment by Firesoul7** [comment]
Those tribes were present before Caesar's invasion. If we mapped the
appearance of all tribes according to when they appeared in historical
records then most of North America would be uninhabited before Europeans
arrived.

**Comment by qweytr** [comment]
Archeological evidence would be fine as well. And being uncolonized doesn't mean being uninhabited. Most of North America already is mostly uncolonized before the European arrival as it should be.

**Comment by Firesoul7** [comment]
I argue that North America being uncolonised like that is largely
inaccurate, and reflects an inconsistency in the treatment of Nomadic
nations. Note that the Oirats get a massive empire, while the Shoshone and
Sioux get handfuls of provinces and the ability to move. This is largely a
vanilla issue however, aswell as one in the mod.

**Comment by qweytr** [comment]
I don't see any inconsistency there. The Oirats were a well established tribal federation with documented history and rulers. Pretty much nothing is known about the Shoshone and the Sioux before 1700, so having them as anything other than migratory OPMs would be unreasonable.

**Comment by PhelanBavaria** [comment]
Thanks for the conversations, but they only reinforced the issues I pointed out.
The vanilla system of uncolonized provinces isn't very nice nor historical.
We have to deal with it in the best way, that's why the question comes up, when do they get the right to become a tribe?
For most tribes we don't have a certain year when they become relevant, the word relevant itself is very sloppy, so we have to define what it means.
If we define it by some government, then we define it by a serious government (such as the Aedui had), which would mean that most trial provinces would be empty or we define it by when we knew about these tribes, which for the most part would be at the time of Caesar.
I'm not happy with either and that's why I started this issue, because I hope that you guys have a better idea.

**Comment by qweytr** [comment]
In my opinion a somewhat centralized government is one of the most important factors for being a country. A bunch of small separate tribes are not enough in my opinion, but it's often impossible to know how united these tribes were. In these situations going by when these tribes are first known of is perhaps the best solution.

**Comment by PhelanBavaria** [comment]
I guess we should go by "when they were first known" and adding a few years to that.
Probably the years I will add to it will be by my own judgement, for example, the Pictones will be appearing maybe 50 years before Caesar, while the Aedui and Arverni will appear a few hundred years before it, even though they all were first reported (at least to my knowledge) by Caesar.

**Comment by PhelanBavaria** [comment]
So, to close this issue, here is how we do it for every nation when we have to decide at which year we make them pop into existence:
For the Celtic tribes I was looking for where their biggest areas of development were at every given time.
That means, a tribe which had a hill fort will be present at the time the hill fort is built.
Since there is rarely exact information on that, I estimated how likely it is and made them appear at the time scientists estimated the construction, or a bit later (about 100 years).
So, it's all estimation of the population size and the development of a center (such as a hill fort).
