### ISSUE TITLE
Merging tags

### ISSUE THREAD

**Issue by qweytr** [PhelanBavaria/ancienttimeline#14]
There are a couple tags that I think should be merged.

First of all, there are currently three Egypts. Egypt, Pharaonic Egypt and Ptolemaic Egypt. I think that should be cut into at least two by merging Egypt and Pharaonic Egypt.

We also have two Persias. The Achaemenids and Persia. I don't think both tags are needed as the Achaemenids were the only Persian empire during the timeline.

**Comment by Firesoul7** [comment]
Merging sounds scary. I prefer instead that Egypt and Persia be removed,
since they are unused.

**Comment by qweytr** [comment]
I'd rather remove Pharaonic Egypt than Egypt, as Egypt just sounds a lot better. I'd also rather remove the Achaemenids, as the country they ruled was Persia and the Achaemenids were just the ruling dynasty. Persia also works better as a name if the ruling dynasty happens to change.

**Comment by Firesoul7** [comment]
I must disagree. Pharaonic Egypt could be renamed from 'Old Egypt' to just
'Egypt' but I really hate the modern Egyptian flag being used in such
ancient times, and if this mod is imported into ET then even if Egypt gets
a proper flag in AT, they'll get the modern Egyptian flag. To me that's
Rome forming Italy level annoying. Modern Egypt is an Arab nation with no
connexion to Pharaonic Egypt. As for your argument about
Persia/Achaemenids. Look at China. Plus, ingame Persia is an Islamic
ex-colony with an ugly flag that has no resemblance to the Achaemenids. I
don't like the color, flag or implication and I strongly affirm my belief
that the Achaemenids should be kept separate from the vanilla and ET nation of
Persia.

**Comment by qweytr** [comment]
Nobody said anything about using the modern Egyptian flag. Of course they would be using a completely different flag. Same goes with Persia. They would naturally not be Muslim and they would be using the Achaemenid flag and the color can be changed as well.

**Comment by Firesoul7** [comment]
But any changes like that would be undone by ET because they would use the same tag.

**Comment by qweytr** [comment]
No. I would make them keep their old flag when ported over to ET.

**Comment by Firesoul7** [comment]
And old color scheme? How?

**Comment by qweytr** [comment]
The old color could be kept as well. That would not be a problem, as anyone playing BC to AD converted saves would anyway have to be using a special ET sub-mod that adds all the tags and cultures from this mod. That sub-mod can also change the colors and flags of any countries.

**Comment by Firesoul7** [comment]
I'm used to using ACA. Changing every example of ACA for PER would be a long and tedious task, and even if it was done I don't see any reward in it. I would support removing Persia and the original Egypt, but I just don't like the idea of removing the Achaemenids or either Egypt that was added. I again point out China.

**Comment by qweytr** [comment]
I have a script that allows me to change every instance of ACA to PER in all files in a fraction of a second, so the effort is not a problem. The Chinese countries are named after the dynasty because there is no other alternative. And Old Egypt sounds a lot worse than Egypt in my opinion.

**Comment by Firesoul7** [comment]
Why not just call the Chinese dynasties 'China'? Have them all as one
country. Old Egypt does indeed sound terrible, which is why I propose that
we remove the ET Egypt and rename 'Old Egypt' to 'Egypt'. This would,
incidentally, be a very simple change requiring the editing of only one
line.

**Comment by qweytr** [comment]
There have been several Chinese dynasties existing at the same time, so they must have different names. For the time periods when all of China has been unified, calling it China would be OK, but then it would be inconsistent with the times when there are several independent kingdoms. Old Egypt could be renamed to Egypt. That would be a pretty much equivalent solution.

**Comment by Firesoul7** [comment]
There has only ever been one ruler of China at any given time. Certainly
there have been rebel states etc, but these hardly count. What I am trying
to argue with China however is that calling the Achaemenids the Achaemenids
is not only acceptable but expected. I am more than happy for Old Egypt to
be renamed to Egypt, if that solution would satisfy you.

**Comment by qweytr** [comment]
I don't really see your point there, but I understand your opinion. Now let's just wait for the other people's opinions before deciding what to do.

**Comment by Firesoul7** [comment]
My point is that Chinese states are named Han, Ming, etc after their
dynasty, and that it is therefore acceptable for the same to be the case in
Iran. But yes, let's wait for the other's opinions.

**Comment by PhelanBavaria** [comment]
I actually agree with qweytr, completely.

**Comment by PhelanBavaria** [comment]
I think as soon as Joe gives his OK on the Egyptians, you can merge them.
Personally I would keep the PER tag and remove the ACA tag, but firesoul seems to feel very strong about it. So I think you both should argue that one out.

**Comment by PanzerfaustJoe** [comment]
I think we should only have Old Egypt and Ptolemaic Egypt, and just leave it at that.

**Comment by yugoslavia45** [comment]
I think there should just be PER and also I think there should just be Egypt and Ploytemy Egypt

**Comment by PhelanBavaria** [comment]
alright, we do following:
EGY = Egypt
EGP = PtolemaicEgypt
ACA = Achaemenids (yes firesoul, I will throw it in your face if this turns out to be more work for us later on)
