### ISSUE TITLE
Flags for Eastern Satrapies

### ISSUE THREAD

**Issue by Firesoul7** [PhelanBavaria/ancienttimeline#16]
These flags don't need to be (and probably shouldn't be) historical. I'd much prefer you use your own creativity, since this is where the very best flags come from. Thanks in advance.

CHS - Chorasmia (Persian)
CLC - Colchis (Using flag in link)
CMN - Carmania (Persian with undertones of nomads)
HDS - Hindush (More Indian than Persian)
SGD - Sogdia (Persian but with nomadic influences. The Bactrian camel was nice, try a stylised or re-colored version of this)

Thanks again

(List has been updated)

**Comment by PanzerfaustJoe** [comment]
I'll do my best, but ancient india is probably the hardest to get flags for, so you will understand if they suck right?

**Comment by Firesoul7** [comment]
I'm asking you to avoid historical accuracy. These flags should feel as I've described, but not actually be such. For Indian influences you could look into Hindu symbols, and even rugs


Sent from my Samsung device

-------- Original message --------

**Comment by Firesoul7** [comment]
Persian influences:
https://www.google.co.uk/search?q=Persian+rug&biw=1920&bih=985&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMI-5644tORxwIVy2rbCh2DcQ_R#tbm=isch&q=Persian+rug+pattern
Nomadic influences:
https://www.google.co.uk/search?q=Persian+rug&biw=1920&bih=985&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMI-5644tORxwIVy2rbCh2DcQ_R#tbm=isch&q=Nomadic+art
Indian influences:
https://www.google.co.uk/search?q=Persian+rug&biw=1920&bih=985&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMI-5644tORxwIVy2rbCh2DcQ_R#tbm=isch&q=Hindu+symbols
Also, this flag would be better for Colchis:
https://www.google.co.uk/search?q=Colchian+flag&biw=1920&bih=985&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMImIa80dSRxwIVqZbbCh2NmwCM#imgrc=wTgssenhnWiYAM%3A

**Comment by Firesoul7** [comment]
Thanks in advance.

**Comment by Firesoul7** [comment]
In the Nomadic influences, what I'm looking for is the animal sculptures. That is the style I'm talking about. You did it extremely well for the Celts and Iberians. Indian influences are the intricate designs that you can see on the page, including symbols of Hinduism. A mix of nomadic and Indian influences would be an extremely stylised animal shape, or one of the animal shapes surrounded by spirals and such. A Persian flag with slight nomadic influences would mainly look like one of the rug patterns, but with animal shapes. Etc. Thanks again.

**Comment by Firesoul7** [comment]
https://www.google.co.uk/search?q=Persian+rug&biw=1920&bih=985&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMI-5644tORxwIVy2rbCh2DcQ_R#tbm=isch&q=Hindu+symbols&imgrc=_ESXplzxNdgDyM%3A

This symbol is especially nice.

**Comment by PanzerfaustJoe** [comment]
After looking, I agree that some need to be replaced, but Aria, Aracosia, Amyrgoi and Gedrosia look fine to me. However, Hindush, Chorasmia, Sogdia and Carmania look horrid, so I will replace those. Will that satisfactory?

**Comment by Firesoul7** [comment]
Aria and Gedrosia are fine and don't need changing, true I would've removed them from the list if I'd noticed them the second time I went through. Amyrgoi however is the worst of the lot, it looks like a modern flag. Aracosia meanwhile is Islamic. Also, what about Colchis?

**Comment by qweytr** [comment]
I think the flags of Aracosia and Amyrgoi are fine. Not everything with a crescent moon is Islamic.

**Comment by Firesoul7** [comment]
I've looked it up and seen where Aracosia flag comes from. It's absolutely fine, I just get a bit distrustful when I see the star and moon because it's often a warning sign that the flag comes from much later. I've redone the Amyrgoi flag myself. It's what I was looking for, and by all means have a look at it and give me your thoughts.

**Comment by Firesoul7** [comment]
Colchis will still need changing. It isn't in the same subzone true, but I've linked the flag I'd like it to have, and I think the flag I chose fits much better with the times and with the history of Colchis.

**Comment by PanzerfaustJoe** [comment]
I will replace Colchis too. I am happy we could come to an understanding on this and not argue. Thank you.

Also, the one you added is fine.

**Comment by PanzerfaustJoe** [comment]
Flags replaced, opinions? Also just in case you didn't notice yet, I added a flag for the Roman Kingdom.

**Comment by Firesoul7** [comment]
The new flags are all excellent. Very clear improvement from originals. The
Carmania flag in particular looks hugely better.

**Comment by qweytr** [comment]
The flags for the Eastern Satraps are done, so I consider this issue closed.
