### ISSUE TITLE
Partially dynamic technological advances

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#17]
qweytr and I had a talk about making the tech groups more dynamic, so the modifiers are not dependent on the tech group.
We would create other modifiers, please add your ideas and I'll include them
## Buildings

Library (partially done)
Road
## Country modifiers

Peace
Exceptional ruler (chosen by rare event)
Stability
## Governments

Every used government should have modifiers to their technology

**Comment by Firesoul7** [comment]
Stability seems a sensible modifier. Stable countries are better at
research.

**Comment by Firesoul7** [comment]
Has anything more been done on this?

**Comment by PhelanBavaria** [comment]
Thanks for the reminder. Some have been done and we all should cosider this issue while creating or using government types and other things that might cause a tech buff.
Events will still have to be created, also buildings.
This isn't a pressing issue though, so it can stay open for a while.

**Comment by qweytr** [comment]
It is not feasible to have buildings decrease tech costs. If have a building that gives e.g. 1% discount on tech, having that building in 100 provinces would already be 100% reduction. The bonus would have to be about 0.01% to not be overpowered, but then that would be completely meaningless for small countries.

**Comment by PhelanBavaria** [comment]
Hum, I see what you mean. But try having that many buildings first, especially if we make it expensive.
Perhaps things like universities could be unique things. Roads could be country modifiers or something.

**Comment by qweytr** [comment]
There are no unique buildings in the game anymore, but it might be possible to make some nonetheless. I wouldn't count on that though.

**Comment by PanzerfaustJoe** [comment]
Yeah, what ever happened to the buildings that you added in extended by the way? They disappeared a while ago.

**Comment by qweytr** [comment]
The building system was completely redone in Common Sense. I haven't yet looked at how adding buildings works now.

**Comment by PanzerfaustJoe** [comment]
I'm sure you will figure it out :)

**Comment by PanzerfaustJoe** [comment]
Temple 
Monument
Stable
Mine
Masonry

A few possible buildings

**Comment by Firesoul7** [comment]
Things work very differently in the game now, I'm closing this issue because I think it's obsolete.
