### ISSUE TITLE
Ideas on units

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#19]
Since we all need to work on units sooner or later, I wanted to know how everybody thinks about this topic.
Right now there are only two units in the mod, stone_age_spearmen and stone_age_clubmen.
My idea would be to have bronze_age_levy for the bronze age for everybody.
In the iron age, or perhaps already in the late bronze age the units grow apart.
So for the Westerners and the Barbarians I would use freemen.
I think especially the Romans will need multiple changes in their units, which, as far as I know, means that everybody else has to have a change in units at the same tech level too.
So maybe I will use different tiers of freemen.
The next problem are horses, they weren't used all that much by the Mediterraneans, Persians and Indians until pretty late, and the Celts mostly used them in combination with their infantry, so no separate units. When would you estimate that we actually implement cavalry units (around which year).
Third issue is artillery, I think we should use them. Maybe making them very weak and expensive, so their only use is to give a bonus during sieges.

**Comment by Firesoul7** [comment]
I think that we should avoid excessive use of generic units. Also, the whole bronze age iron age stone age thing was sort of completely inaccurate. As for cavalry, I point out that Bactria was famous for its cavalry, as were the Scythians. I think we should look into when countries get cavalry on a case by case basis. Finally, I agree that there should be artillery. 

Sent from my Samsung device

-------- Original message --------

**Comment by PhelanBavaria** [comment]
Scythians were nomads, and I think Bactrians too? Which I already had included in my statement.
As far as I know we can't just give cavalry to earlier to Scythians than to Celts or others. They all have to get them at the same tech level.
I'm aware that bronze age etc. isn't very accurate, that's why I used it, because I'm not quite sure about this whole thing yet.

**Comment by Firesoul7** [comment]
Actually nations can get cavalry at any level, just as with any unit. A
nation unlocks cavalry when they get their first cavalry type unit, and any
unit can be made unique to a culture, religion, tech group, etc. I've
created units in the past, don't worry I know how they work.

**Comment by PhelanBavaria** [comment]
I did too, but when I gave a nation cavalry units later, then they just got the cavalry unit of a different nation assigned.

**Comment by Firesoul7** [comment]
You likely did it wrong. I'll look into it at some point. I know for
certain that countries can get cavalry at different tech levels.

**Comment by qweytr** [comment]
The stone and bronze age units are very accurate in my opinion. After all, the biggest improvements in weapons at that time happened when new better metals were introduced. 

Having generic units is not a problem, when no better alternatives are available. I don't quite like the vanilla system where there are units like Indian Spearman, Asian Spearman and South American Spearman. That is basically the same as everyone having just Spearman. Of course more specific units should be added whenever possible, but I don't expect there to be specific units for all regions for all times.

First cavalry units should be chariots, which were first used by the Scythians around 2000BC. This means that there will be about 1000 years of no cavalry, when started from the earliest date, but I don't think that is a problem.

Artillery should be in too, but not available until very late. They should be made very weak in battle and useful pretty much only for sieges.

**Comment by PhelanBavaria** [comment]
I tried it over a year ago, chances are that they improved it so you can give everybody horses on different tech levels. Would be great if it actually is possible.

**Comment by qweytr** [comment]
It has always been possible to give countries horses at different times. In vanilla, the American natives don't start with cavalry, while the rest of the world does. ET does this as well.

**Comment by PhelanBavaria** [comment]
Yes, but that is because they have different tech levels, I was talking about giving them cavalry at different tech levels.

**Comment by PhelanBavaria** [comment]
Sorry, I just noticed the stupidity in my sentence, I was talking about giving certain people cavalry at tech level 4 or whatever and other people cavalry at tech level 10. That's what I meant with different tech levels (it's late and I did a lot today alright, don't judge)

**Comment by qweytr** [comment]
That is exactly the case both in vanilla and in ET. It is possible and always has been.

**Comment by PhelanBavaria** [comment]
Hum, well in vanilla they all get cavalry at the same time at tech level 1.
Just to really eliminate every doubt of misunderstanding what you are saying:
We could give the Scythians cavalry at tech level 50 and the Celts at level 70? (arbitrary numbers)

**Comment by qweytr** [comment]
There are no Native American cavalry units available at tech 1, but yes, what you said in your example can be done.

**Comment by Firesoul7** [comment]
There have been a few comments since it but... Having a stone/bronze/iron
age system really isn't historical. It was very common for example for the
troops of a given military to have iron weapons and bronze shields, or for
their troops to have a mix of iron and bronze weaponry. The idea that one
day some guy discovered a new material and then that material was used for
everything is simply wrong. It also creates an image of linear advancement,
that bronze - iron was some huge tech leap when it really wasn't. For
centuries after iron weaponry had been introduced people were still
debating whether bronze or iron weapons were better. Many iron weapons were
after all inferior to bronze weapons at that time. If the process is then
extended to a 'steel age', then I ask you to have a look at a medieval
sword. You'll notice it has a core of iron and an edge of steel. Placing
history into eras such as stone age, bronze age, etc isn't historical, and
improvements in troops should be based principally on tactics, not
weaponry.

**Comment by qweytr** [comment]
It's true that the improvement from bronze to iron wasn't that huge, but it was among the only significant technological developments during the period.

**Comment by PhelanBavaria** [comment]
I didn't argue in favor of a store/bronze/iron age system :P
I just used this type of age measurement to vaguely tell when I think certain units should be present.
Also, it seems like those types of ages were categorized by what the current main tool for cutting was.
Also, it's a measurement of period which doesn't stick to years, but rather to the usage of something, which somewhat represents the difference in tech levels between people.

**Comment by Firesoul7** [comment]
The problem is that it doesn't do that. The stone/bronze/iron age system is
typically used as a global system. For example, no one says that the native
Americans lived in the stone age, even though they had no metals. The
Hittites made extensive use of iron during the 'bronze age', and the 'dark
ages' took place during the Islamic golden age. The stone/bronze/iron age
system is eurocentric and really doesn't work. I hold that advancements in
troop technology in AT should be based on tactics, not equipment.

**Comment by qweytr** [comment]
I have seen the ages used like that all the time. For example with the pre-history of my own country, Finland, we don't talk about Iron Age until 500BC, while on other parts of the world the Iron Age began already in 1200BC. 

Tactics could of course be also used to descripbe different units, but there is so much time to cover that there simply aren't enough tactics to get enough units. Also, many of the tactics were situational and an army could change from one tactic to another if required. The number of tactics that can be used for units isn't really that big.

**Comment by PhelanBavaria** [comment]
Considering we work on units right now, I'd like to finalize this issue.
Rather than having a name for a unit chosen by a certain soldier type, I would suggest using a term that groups them together.
For example, using Phalanx for the Greeks seems fine, that was the main formation of them.
In the case of Celts and others it's a bit different though, for them I would rather use names like "Freemen" (warriors chosen among the free population), "Warriors" (men trained for the army), "Champions" (warriors trained for the army with improved equipment). Here we also have to consider that slingers and cavalry were included and no separate units.

So use terms that round up what type of units are included in that unit.

**Comment by Firesoul7** [comment]
Sure, but at the same time we should seek to maximise the number of units
available to each nation.

**Comment by Firesoul7** [comment]
And something of a note-to-self, but appropriate here, I need to add the
unit_type for the units I've added.
