### ISSUE TITLE
Longer Claim fabrication

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#2]
Claims should take longer to fabricate.
The idea is that, instead of fabricating documents that proof a claim to a province, you have to spread the idea that that land is by right yours, which would probably take longer.

Which variable in defines.lua?
How much increased?

**Comment by Firesoul7** [comment]
I'm not sure. Claims were much more flimsy back then, all that would be
required really would be convincing your own people that a given province
ought to be theirs. I really don't know though.

**Comment by PhelanBavaria** [comment]
well, as far as I know we can't disable claim fabrication, so we might as well at least tweak it to be half decent. Also, that what you said was what I meant, instead of fabricating a claim, you have to convince your own people, which in the game can use the same mechanic.

**Comment by Firesoul7** [comment]
OK, but then logically claim time would be in inverse ratio to country
size. I don't know how to do that

**Comment by PhelanBavaria** [comment]
I want to close this proposal as soon as qweytr gives his opinion on it.

**Comment by PanzerfaustJoe** [comment]
Personally, I think it should be shorter, as the farther in time you go back, the more violence their was.

**Comment by PhelanBavaria** [comment]
Not really, Celts for example fought many wars, but most of those wars were more like a modern football match than a fight to the last man.
I think it fluctuated throughout history, Napoleons time was probably among the violent and bloodiest ones.

**Comment by qweytr** [comment]
I don't really have an opinion about this one. Claims weren't really important back then, as there was no real need to justify ones conquests. You could either make claiming easier to simulate the fact that it was no problem getting a CB back then or just make claims useless by giving everyone acceptable CBs against everyone.

**Comment by PhelanBavaria** [comment]
Maybe you are right, there was the need to justify a war, but it could be represented otherwise than with claim fabrication.
Alright, so the issue is closed, claim fabrication will be rendered nearly useless by giving everybody according CB's.
