### ISSUE TITLE
World Wonders

### ISSUE THREAD

**Issue by Firesoul7** [PhelanBavaria/ancienttimeline#20]
This issue is to list as many world wonders as possible that were built during or shortly after the time period of AT, they can then be discussed in a separate issue.

Pyramids
Stonehenge
Library of Ashurbanipal

**Comment by PhelanBavaria** [comment]
Lighthouse and Library of Alexandria
Mausoleum of Helicarnassos
Hanging Gardens of Babylon
Colossus of Rhodes
Zeus statue in Olympia

**Comment by Firesoul7** [comment]
If we're to include the seven wonders, then the Temple of Athena.

**Comment by PanzerfaustJoe** [comment]
I like the idea of constructing wonders. I actually suggested it earlier this year. They should give good bonuses to whoever builds them, and should work like the canal construction events.

**Comment by yugoslavia45** [comment]
Yeh that would be cool as a great projects instead of the canals

**Comment by qweytr** [comment]
Since a new issue was created about this topic I'm closing this one.
