### ISSUE TITLE
Units for Greeks and Persians

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#22]
Units have to be created for these two peoples.
Please submit ideas below.

**Comment by qweytr** [comment]
The main infantry units should be Phalanx for Greeks and Sparabara for Persians.

**Comment by Firesoul7** [comment]
Certainly, but there need to be more. In particular different kinds of
phalanxes, with different equipment. I'll look into the matter.

**Comment by PanzerfaustJoe** [comment]
Persian Immortals
Persian Elephants
Greek Hoplites
Macedonian Cavalry
Xiphos Warrior
Greek Peltasts

**Comment by qweytr** [comment]
The unit names are better without the cultural prefixes, but otherwise they are great.

**Comment by PanzerfaustJoe** [comment]
Thanks, I wasn't saying to put the cultural prefixes in the game, but to help you guys in case some of you didn't know what nation they were for.

**Comment by qweytr** [comment]
The Persians used a lot of Greek mercenaries in the war against Alexander, so Hoplites, Phalanxes and Peltasts should probably be available to them as well.

**Comment by Firesoul7** [comment]
Yes, but these were mercenaries. If possible I would like to make it so certain units 


Sent from my Samsung device

-------- Original message --------

**Comment by Firesoul7** [comment]
Are only available as mercenaries. I'm not sure if that can be done or not. 


Sent from my Samsung device

-------- Original message --------

**Comment by qweytr** [comment]
Practically all troops were mercenaries back then, but in EUIV standing armies are more important. Persians having Greek mercenaries in reality would translate to Persians having Greek units in the mod.

**Comment by Firesoul7** [comment]
I don't like the ingame system whereby one can only have one infantry unit,
one cavalry unit, etc at a time. Also, the Greek mercenaries that Persia
had came primarily from their holdings in Anatolia, so I would create
unique units all the same.

**Comment by PhelanBavaria** [comment]
As far as I know you can have multiple mercenaries unit types.
So given that the Greeks could select Legionaries, they could have Hoplites as normal infantry units but recruit Legionnaire mercenaries.

**Comment by Firesoul7** [comment]
What I would also like to do thinking about it is to have multiple versions
of the same troops, with slightly increasing stats, under the rationale of
better training and increased army size. I believe this necessary given how
little technological advancement there was at the time. Technologies
themselves could likewise be split, say into 'bronze spears (1 through 10)'

**Comment by Firesoul7** [comment]
Hmm... I don't like the idea that Greek states could select Roman legions
as their main troop type. I would want to limit such units by culture.

**Comment by PhelanBavaria** [comment]
I believe you can, it was just an example though.
I think having better units can be achieved by choosing the right ideas for that.
If you could just select better units then everybody would select the best units.

**Comment by qweytr** [comment]
By the way, units must be unique to any tech group in order to be available as mercenaries. I noticed that many of the units added so far are not tech group specific, so they can never appear in the mercenary pool.

**Comment by PhelanBavaria** [comment]
Could we do things like only make it possible for Greeks to select Hoplites as units but also make them able to recruit Celtic mercenaries and stuff like that?

**Comment by Firesoul7** [comment]
I think that should be possible, yes. I'll need to fix the units I've added
first of course, but it should work.

**Comment by qweytr** [comment]
As far as I know you can't have units of other tech groups as your mercenaries, but I'm not sure about that.

**Comment by Firesoul7** [comment]
Ah, I'd forgotten that the Celts weren't in the Mediterranean group

**Comment by qweytr** [comment]
I'm closing this one, as there's now a new issue for units.
