### ISSUE TITLE
Making it possible for Alexander to succeed

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#23]
As of yet, playing as Alexander the Great, even with the change of him being a 6 6 6 2 general, it's impossible to win.
Some better buff should be added and/or a debuff to the Achaemenids.

**Comment by qweytr** [comment]
The scenario is not finished yet. Persia shouldn't control any provinces in Europe and Thrace should be under Macedonian control.

**Comment by Firesoul7** [comment]
You said that in 335 BC the Achaemenids shouldn't have any provinces in
Europe. They don't.

**Comment by qweytr** [comment]
Currently the Achaemenids own many provinces in Thrace until June 335BC. The Alexander bookmark is in October 336BC, so the Achaemenids still own those provinces. In reality the Achaemenids lost Thrace in about 479BC.

**Comment by Firesoul7** [comment]
OK, you didn't explain that. I got the impression that you were saying that
the Achaemenids lost their European provinces in 335. The problem is who to
give these provinces to if not the Achaemenids.

**Comment by qweytr** [comment]
https://en.wikipedia.org/wiki/Macedonia_(ancient_kingdom)#/media/File:Map_Macedonia_336_BC-en.svg
According to Wikipedia those territories were dependent on Macedon at Philip's death, so you could just give them to Macedon. That would also make it easier for Macedon to succeed against the Achaemenids.

**Comment by qweytr** [comment]
https://en.wikipedia.org/wiki/Philip_II_of_Macedon#/media/File:Map_Macedonia_336_BC-en.svg
According to this map those territories were dependent on Macedon at Philip's death, so you could give them to Macedon. That would also help them succeed against the Achaemenids.

**Comment by qweytr** [comment]
Wikipedia article about Seuthes III states: "After Philip's death in 336 BC, many of the Thracian tribes revolted against Philip's son Alexander III, who waged a campaign against and defeated the Getae and King Syrmus of the Triballi. All other Thracians sent troops to join Alexander's army."

So you could also give the inland Thracian to Triballi with Macedonian cores or keep them Macedonian but controlled by rebels. Anyway it seems that most of Thrace remained loyal to Alexander and should be directly owned by Macedon at the Alexander bookmark.

https://en.wikipedia.org/wiki/Syrmus
https://en.wikipedia.org/wiki/Seuthes_III

**Comment by yugoslavia45** [comment]
If we are doing that hiw about giving akexander a boost to naval force
limit to blockade the dardnells

**Comment by Firesoul7** [comment]
What about before that, from when Achaemenids lost the territory to when
the area became a Macedonian dependency?

**Comment by PanzerfaustJoe** [comment]
Make it simple and give Macedon a buff like you did the Mongol Empire.

**Comment by Firesoul7** [comment]
Qweytr, we need you to add a series of huge empire modifiers, like was present in ET (but doesn't seem to work in AT). Ideally these modifiers should be even more devastating. Achaemenid manpower has to be absolutely destroyed, or there is no way that Alexander could win. I've already boosted Alexander as much as I feel I can.

**Comment by qweytr** [comment]
The problem is currently that the Achaemenids can't win. I admit it should be hard, but possible. Sure the Achaemenids get currently about 160k troops, but that doesn't matter when the Macedonian 17k wipes the floor with them.

**Comment by Firesoul7** [comment]
The Achaemenids win every time though. Macedonian troops are very powerful
but they just get overwhelmed. I've never seen Alexander win.

**Comment by qweytr** [comment]
That might be due to the instant annex system. The Achaemenids can just avoid the Macedonian troops and annex all of Macedonia without fighting at all. The Achaemenids stand no chance of winning any battles though. 

One thing to slightly weaken Persia would be to reduce their size a bit. Nabataeans and Massagetae should be independent and Cyrenaica, Colchis, Pontus and Albania perhaps as well. For the latter I haven't found any concrete sources to support their independence, but I haven't found any sources to support them being Persian either. Anyway, I think that making those countries independent would help balance the scenario and make the regions more interesting.

I can add negative modifier for large empires, but I won't make them any harsher than they are in ET. Also, there should be a way of getting rid of the modifiers, which could be a certain technology level like in ET.

**Comment by PhelanBavaria** [comment]
It isn't possible for Alex to succeed right now. I tried to put all my troops in Edirne, letting the Persians come 10k stacks at once and blockade them so they couldn't reinforce. I got them down to 0 manpower, before their fleet destroyed mine and they crushed me with 75k men at once.
I had Alex as leader and the crossing -2 penalty against them, but still they won.
I think if we give them the same modifier that they would get in ET, then one could win.

**Comment by Firesoul7** [comment]
I'm not sure those modifiers should ever disappear. Perhaps the boundaries
could be increased at later tech levels. The Achaemenids don't avoid
Macedonian troops, they send in huge armies relentlessly against Macedonian
stacks. Once the main army is defeated they invade Macedon and stop any
more armies from being created. I'm yet to witness the Achaemenids
completely taking over Macedon, but from the Rise of Alexander bookmark
they definitely win the war. The Nabateans are already independent with the
bookmark, and Massagetae quickly gets its independence after it. As for the
others, I would prefer to keep them part of the Achaemenids due to various
historical reasons.

**Comment by qweytr** [comment]
I tried playing as the Achaemenids and couldn't come even close to winning with 160k against 20k. And if you have 10k against 75k it should be practically an unwinnable battle even if you have Alexander. I'd say we must reduce both the Achaemenid army sizes and Alexander's bonuses.

I'd like to hear the historical reasons for keeping these provinces in the Achaemenid Empire, as I haven't found any.

**Comment by Firesoul7** [comment]
Try observing what happens then using the observe cheat.

**Comment by Firesoul7** [comment]
Cyrenaica is considered to be part of Egypt at present. It could perhaps be
removed and made independent, but that would be Joe's job, not mine.
Colchis already gains independence in 335, the time you originally said,
and the same time as Massagetae and Pontus. Albania cannot really be added
at present since it was under the rule of Media Atropatene following
Alexander's conquests. Since Alexander's borders for Media were based on
earlier Achaemenid borders, the current situation seems reasonable. I would
welcome sources to the contrary.

**Comment by qweytr** [comment]
Cyrenaica was an alliance of five Greek colonies. It was conquered by Persia in 525BC, but it's not certain whether or not it was still a part of it in 335BC. I didn't say Colchis, Massagetae and Pontus gained independence in 335BC. I said they likely were independent in 335BC meaning that they would have became independent some time earlier. Alexander never conquered Albania, so making it independent wouldn't be a problem. This map is the best source I have. 

Colchis is the only country for which there are direct sources about its independence. https://en.wikipedia.org/wiki/Colchis "the Colchis people appear to have overthrown the Persian Authority, and to have formed an independent state" Unfortunately this is not dated, but we can assume it happened sometime between 500BC and 350BC.

http://worldhistorymaps.info/images/East-Hem_335bc.jpg This is the best source I have for the other countries, as all other maps of the Achaemenid Empire are dated at when the empire was at its greatest extent. http://sitemaker.umich.edu/mladjov/files/alexandros323nbc.jpg This is a map of Alexander's Empire and you can see that it excludes Albania.

Also, one thing I think that might make it harder for Alexander is that he starts at war. In real life hi didn't start his invasion of Persia until 334BC. He subjugated the Thracian tribes and consolidated power in Greece before invading. Currently there's no chance for that to happen in the mod.

**Comment by Firesoul7** [comment]
It might indeed be wise to push back when the war with the Achaemenids
started. The problem is that accurate dating is difficult. Philip after all
started the war in reality.

**Comment by qweytr** [comment]
Also, the Bosporan kingdom was independent at least from 438BC onwards, if not earlier. https://en.wikipedia.org/wiki/Bosporan_Kingdom

I was also thinking that we could increase the autonomy in the Achaemenid provinces to simulate the satrapy system.

**Comment by PhelanBavaria** [comment]
I think we have to push the invasion back. Even if Philip declared war, I think we should make a difference between real life war and EUIV war, since it probably took the Persians some time to assemble their army, but in EUIV they don't they have them ready right on the border.
We shouldn't forget that the conquest of the Achaemenids wasn't a walk in the park, so I think the right balance would be that Macedon conquers Asia minor and perhaps Egypt, but fails. I think the least common cases should be that they either loose right away or conquer everything.
I agree with increasing autonomy, but let's wait till all the other changes are in place and we'll see how well balanced it is. Then we can increase autonomy if we have to.

**Comment by Firesoul7** [comment]
Yes. I agree with all of that. I think that if autonomy is increased
though, then it should be to 25 percent. 50 percent at the most. Not the 75
percent that you suggested to me.

**Comment by PhelanBavaria** [comment]
I just said, let's increase the autonomy if we have to. Maybe we don't need to increase it at all.
My suggestion of 75 was without the other factors like huge empire modifier, making the Persians bigger and giving Alexander more time to prepare.

**Comment by Firesoul7** [comment]
Every test that I've done shows that Alexander wins the war, but only takes Asia Minor. I think that this is the best result we can hope for, and Alexander certainly succeeds, while the Achaemenids are not destroyed, and in most cases are able to recover some of the land they lost. I believe that historically Alexander would have taken Asia Minor no matter what, and that this system will only be improved by the addition of the systems that determine how many successors will appear, and by improvements to rebels. I therefore consider this issue closed.
