### ISSUE TITLE
Celtic and Iberian flags

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#27]
Flags ToDo:
LCT = "countries/Licates.txt"
COT = "countries/Consuanetes.txt"
RUC = "countries/Rucinates.txt"
CTN = "countries/Catenates.txt"
ETO = "countries/Estiones.txt"
BGT = "countries/Brigantii.txt"
LIZ = "countries/Leuni.txt"
TUI = "countries/Tulingi.txt"

**Comment by PhelanBavaria** [comment]
New flags needed

**Comment by Firesoul7** [comment]
All the countries in this list have flags. This issue can be reopened if flags are needed for nations which are created later in this region.
