### ISSUE TITLE
Carthage Border History

### ISSUE THREAD

**Issue by PanzerfaustJoe** [PhelanBavaria/ancienttimeline#28]
Ok, I have two people telling me different things. Bavaria says they didn't own as much as I originally gave them, qweytr says they did. Honestly, I can't find consistent sources, as every map and article I read says something different about what they controlled. We need to discuss this.

**Comment by qweytr** [comment]
I'll post here the same sources I sent Joe.

World map 335BC http://worldhistorymaps.info/images/East-Hem_335bc.jpg

Wikipedia page about Carthage. https://en.wikipedia.org/wiki/Ancient_Carthage "By the beginning of the 5th century BC [...] the city had conquered most of the old Phoenician colonies, subjugated the Libyan tribes (with the Numidian and Mauretanian kingdoms remaining more or less independent), and taken control of the entire North African coast from modern Morocco to the borders of Egypt (not including the Cyrenaica, which was eventually incorporated into Hellenistic Egypt)."

I'd say that at least the North Arfican coast should be owned by Carthage, but the inland provinces should be owned by Numidian and Mauretanian kingdoms. I have no idea when Carthage conquered the Spanish coast, but according to the map, they had already done that by 335BC. At least for North Africa there are few better alternatives, as there is very little information about any other kingdoms in the area.

**Comment by qweytr** [comment]
According to https://en.wikipedia.org/wiki/Carthaginian_Iberia there was Carthaginian presence in Iberia already in 575BC, but it seems like most conquests there weren't done until 236BC. This map shows the extent of Carthage in 265BC, before the Carthaginian campaigns in Spain. https://en.wikipedia.org/wiki/Carthage#/media/File:Carthaginianempire.PNG I can't find any information about any additional conquests between 575BC and 265BC, so unless additional sources are found, I'd say our best bet is to go with the 265BC borders for 336BC.

**Comment by PhelanBavaria** [comment]
I think I told you that they shouldn't own the whole coast, just harbor cities. So they should own some provinces with a modifier, else I think Carthage will be OP.
As far as I read the Carthaginians had control over parts of Iberia in 575 BC but lost that control later on. The first time they reconquered it was with Hannibal's father.
I'll try to find that source again and then I'll post it.
(btw, I like using worldhistorimaps too, but they often aren't all that accurate)

**Comment by PanzerfaustJoe** [comment]
Ok that's good, we need to all agree on something before I make anymore changes to Carthage.

**Comment by Firesoul7** [comment]
For my part, I believe that anything not controlled by Carthage should be
controlled by someone else.

**Comment by PhelanBavaria** [comment]
http://www.ancient.eu/uploads/images/108.jpg?v=1431030119
This is a map of all the Phoenician (and also Greek) colonies.
I think most of those colonies should be independent and slowly be taken over by Carthage.
I'll try to write a modifier for such colonies in provinces, so that the autonomy can't drop below a certain number, since they didn't occupy all of the province and it was mostly just one city for trading.
I think you'll have to look up those colony names to get some more information out of them.
As for the other parts, look at https://en.wikipedia.org/wiki/Numidia, also look at the links there for the other people in the area.

**Comment by qweytr** [comment]
According to Wikipedia most of the Phoenician colonies had become under Carthaginian influence by the 5th century BC, so I don't think they need separate tags. As for Numidia, it became independent from Carthage in 202BC, long after Alexander. The inland provinces should be owned by the Massylii and the Masaesyli, but Carthage should control the coasts.

**Comment by PhelanBavaria** [comment]
I don't think that they should own the entire coast, at least not from the start. Perhaps they can own it later, of when we know of that they had multiple colonies along the coast.

**Comment by qweytr** [comment]
Not necessarily the entire coast, but at least the provinces with Phoenician colonies on the map you linked.

**Comment by PhelanBavaria** [comment]
Good, so we agree. Provinces that had colonies should be owned by Carthage, the rest of the land by the Massylii and Masaesyli and ?Moors?, which should start to appear around 400 BC.

**Comment by qweytr** [comment]
Yes. Though Moors is a more modern term. Mauri would be more contemporary.

**Comment by PanzerfaustJoe** [comment]
Something new has come up, I need to add some provinces to Carthage in Iberia so it will take away from a few Celtic tribes, I just wanted to get the OK from you Bavaria before I do this. Also I am not sure the Mauri existed in BC, I can only find record of them in AD. I think they were too small before to be notable.

**Comment by qweytr** [comment]
https://en.wikipedia.org/wiki/Mauretania
According to Wikipedia the Mauri formed the kingdom of Mauritania in the 3rd century BC. This suggests that the Mauri people existed some time before that.

**Comment by PhelanBavaria** [comment]
You can change the owner and controller when you know that they had a serious grip on the majority of the province. If they only had one trading port there, then it should stay with whoever owned it.
You will probably have to do a lot of research on the cities there since most maps aren't accurate.

**Comment by qweytr** [comment]
Control of the rural areas is not necessary for province ownership. Control of the most important city in the region is enough and many of those trading ports were the most important city of the region just because they are often the only ones we know of.

**Comment by PanzerfaustJoe** [comment]
I think it would be safe if I just left Iberia in control of the celts. Their isn't enough proof to show that the Carthaginians had "control" over any provinces. They seem to just had some influence, but that is all.

**Comment by PanzerfaustJoe** [comment]
Also, thanks for the link qweytr, I never thought to look at that page.

**Comment by qweytr** [comment]
But the question remains when did Carthage gain control of the Spanish coast. Many maps show that Carthage owned it in 265BC. Wikipedia states that Carthage colonized Iberian peninsula in 575BC, but there are no records of any further expansion between 575BC and 265BC. Bavaria said he would look for sources about Carthage losing and regaining provinces there, but he hasn't showed me any so far. Unless he finds additional sources I think we should go with the 265BC borders for Carthage.

**Comment by PhelanBavaria** [comment]
Alright, so I found this map http://www.ancient.eu/uploads/images/172.png?v=1431030823
I think you'll have to do some research on which cities were found when on the Iberian coast, and when they became so important that it's justifiable to take those provinces away from the natives.

**Comment by qweytr** [comment]
That exactly is the map that shows that Carthage already controlled the Spanish coast by 265BC, but it doesn't tell when Carthage gained control of it. There's not enough information available about when those cities were founded. In any case we must make those Carthaginian at some point, so we could either go for 575BC or for a random date. I don't really like picking a completely random date, as 575BC has at least some sources backing it up. So if no other sources are found to back up any other date, I think we should go for 575BC.

**Comment by PhelanBavaria** [comment]
Alright, let's do that, but keep the cores of the natives in. Also we still need to create that province modifier to simulate that they were just trading ports and no province capitals.

**Comment by PanzerfaustJoe** [comment]
I think I will just leave carthage in control of parts of north africa, and give trading posts to them in iberia when we have done a little more research and created the modifier.

**Comment by Firesoul7** [comment]
Since this issue is about the borders, and not about the trading posts, modifiers, etc, can this issue be considered closed?

**Comment by PhelanBavaria** [comment]
I think so, Joe, can you close this issue if you think that everything is settled?

**Comment by PanzerfaustJoe** [comment]
Yeah, I think we are good.

**Comment by PanzerfaustJoe** [comment]
Yeah, I think we are good.
