### ISSUE TITLE
Decrease of Nationalism

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#3]
Non-cored provinces shouldn't give as much (if any) nationalism in order for Empires such as Macedon to work.

**Comment by Firesoul7** [comment]
I don't know. Macedon didn't exactly last, and all empires tended to be
extremely decentralised and fragmentary. I think given the length of the
timeline and issues with colonisation and blobbing that we need more
nationalist rebels, not less. As for Macedon, they could be given events to
auto-core provinces. Then of course there would need to be events for
successor kingdoms, although that's largely a separate issue.

**Comment by PhelanBavaria** [comment]
The successor kingdoms will be events, I think.
I think rather than having nationalistic rebels popping up depending on the revolt risk in the province, we should write events for great rebel generals. Most of the times when there was a big revolt it was caused by instability, but then there was a charismatic guy who inspired the people to revolt.
That would make revolts less predictable, less common, but harder to defeat.

**Comment by Firesoul7** [comment]
Sure, but I think we should have both.

**Comment by qweytr** [comment]
Nationalism wasn't really a thing during this mod's timeline, but if it's decreased, we must add other ways to make large empires less stable.

**Comment by PhelanBavaria** [comment]
Yes, that's why I suggest rebels by events. Maybe making some rebels based on province and country size. For example, countries that occupy a certain province in the Parthian area and are of a certain size, might get Parthian rebels. Sadly there is no way to just split a country between parties dynamically, like in the case of Alexander's Empire, or the Frankish Empire.
But maybe there is another way we could achieve this, by creating theoretical nations (e.G. Gaul) that can split when a ruler dies, or which get a rebel king that tries to create this country.

**Comment by PanzerfaustJoe** [comment]
Lysimachus was one of the successor kingdoms, and should appear by event, to guarantee it to happen.

Also, during the Rise of Alexander, were we going to give Macedon some "Mongol Empire" type bonuses so that they can obliterate the Achaemenid Empire?

**Comment by Firesoul7** [comment]
They will get bonuses, as to the scale of those bonuses, this has not been
decided yet

**Comment by Firesoul7** [comment]
What is the word on this issue?

**Comment by PhelanBavaria** [comment]
Let it just linger a little longer, I worked on some models of rebels by event, when they are done then we can decide about this again.

**Comment by Firesoul7** [comment]
This is a really old issue, can we finally close it yet?

**Comment by qweytr** [comment]
I think this can be closed.
