### ISSUE TITLE
Successor state flags

### ISSUE THREAD

**Issue by Firesoul7** [PhelanBavaria/ancienttimeline#30]
CSD - Cassander
LYS - Lysimachus
NTG - Antigonus

**Comment by Firesoul7** [comment]
PTL - Ptolemy

**Comment by PhelanBavaria** [comment]
Isn't this done? If so, please close it.

**Comment by Firesoul7** [comment]
It isn't. Ptolemids still have no flag. Unless I'm mistaken

**Comment by PanzerfaustJoe** [comment]
Ptolemy does have a flag, you must have changed the tag or something. When it was Ptolemy, everything was working.

**Comment by Firesoul7** [comment]
EGP did indeed have a flag, but it was too Egyptian. With the new PTL tag I
want a more neutral flag. As of present however they don't have a flag at
all.

**Comment by PanzerfaustJoe** [comment]
I will get to work on it sometimes this weekend, right now I am adding in the Mauri

**Comment by Firesoul7** [comment]
Don't worry, I've dealt with it myself.
