### ISSUE TITLE
semi-fixed capital for province assignment of the diadochi and other related things

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#33]
I want that everybody votes on these issues.
1. capitals (the first provinces the diadochi get) are totally random right now, should it remain like this or be changed, so the diadochi get a preferred capital and if that is not available, they will choose a capital in a certain region.
2. color of Antigonus should change, it's the same as Macedon and too similar to Ptolemy
3. slowing down the province capturing. This would make the wars longer because people hold territories. The suggestion is 178 days (as much as it is in ET).

**Comment by PhelanBavaria** [comment]
1. I'm in  favor of making it semi-fixed, I think they would have pretty much always chosen the same capital.
2. in favor
3. in favor

**Comment by qweytr** [comment]
1. Semi-fixed.
2. In favor.
3. In favor.

**Comment by Firesoul7** [comment]
1. against. I want the system to be dynamic. The generals chose the capitals they did essentially because they were there at that time. Wherever they would happen to be is where they would make their capital.
2. in favour, but I'm not the one who is going to change it.
3. completely against. The whole point of this system is to be fluid, for provinces to rapidly change hands.

**Comment by Firesoul7** [comment]
If this is the system you want, I'll just make events to hand out all the provinces according to where they ended up, and remove the Diadochi wars.

**Comment by qweytr** [comment]
We're not suggesting removing anything. The current system is good, even though there are some problems with it. It just needs to be tweaked a bit.

**Comment by PhelanBavaria** [comment]
So 1 and 2 are decided.
For the 3rd, I think you might be right that half a year is too long, but it shouldn't be instant as it is right now. Perhaps we can agree to put it on 60 days (2 months)?
Also in my opinion the war should last longer, that might be achieved by changing the CB type, what do you think?

**Comment by qweytr** [comment]
Changing the CB could also help make the wars last longer. What CB do they use currently or do they use any?

**Comment by PhelanBavaria** [comment]
They don't use any, but I think they should use the one in which you need to win the majority of the battles. That happens quite fast actually, one diadochi beats the other and the other can't recover a huge army anymore and then they get beaten again and again.

**Comment by qweytr** [comment]
It's easy enough to change, so we could try that out and see if it helps.

**Comment by Firesoul7** [comment]
Or the one that involves taking their capital maybe?

**Comment by PhelanBavaria** [comment]
That wouldn't work because you just own it after a month and their capital would change.

**Comment by Firesoul7** [comment]
Well, yes. That's the point. It might discourage the AI from making peace
so quick if the victory condition isn't really possible, but seems
possible.

**Comment by qweytr** [comment]
No. The instant annex system causes the AI to think the war is stalling making it more willing to end the war. Even if it's winning, the AI doesn't know it as it has no warscore from occupations. With a CB that gives warscore from battles the AI might know when it's winning and continue the war, but I still think that the annexations shouldn't be instant.

**Comment by PhelanBavaria** [comment]
Alright, so the final decision is to give them a different CB and if that doesn't work, then the mtth between province conquest and owning will be increased.

**Comment by Firesoul7** [comment]
A final decision has been made. This issue is closed.
