### ISSUE TITLE
Cult of Serapis

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#34]
Add this religion since it was the religion of the Ptolemaic Kingdom.

**Comment by Firesoul7** [comment]
I've added it, but I think I'll change the color before considering this issue closed. The current color is a lot more... white... than I had intended.

**Comment by Firesoul7** [comment]
I've changed the color to a golden type thing which I think fits them well. This religion is therefore now done.
