### ISSUE TITLE
generic vs. specialized idea names

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#37]
So I had a thought about adding ideas to the game and I talked with qweytr and we seem to disagree.
My 3 additions to the idea groups would be Ambush, Professional Army and Conquest.
We discussed the Ambush idea group because he things a general defensive idea group would be better, since both are pretty much the same when it comes to the effects.
Now here is the question on how we do it, do we use generic names like "Defensive Ideas" or more specialized names like "Ambush Ideas"?

**Comment by qweytr** [comment]
I have nothing against the vanilla idea groups names. The names of the individual ideas and descriptions will have to changed, but I think we don't need to replace any of them. 

Additional ones could be added, but Ambush is too similar to Defensive. We could include both, but they would inevitably end up having too similar effects. There were plenty of countries that focused on defending their countries though means other than ambush tactics. For example the Chinese were already building large walls to keep the Xiongnu away. A name like Ambush ideas wouldn't fit situations like this at all and would end up fitting only a small portion of countries.

Names like Professional Army and Conquest are better. Professional Army is pretty much equivalent to Quality ideas, which could be renamed to that and be changed a bit. Conquest ideas would fall somewhere between Offensive and Influence. I don't think it is different enough from them, but it is also not similar enough to directly replace one or the other.

**Comment by Firesoul7** [comment]
I don't like 'Professional Army Ideas' simply because it has too many words. I also agree with Qweytr (yes, I surprise myself lol) about ambush ideas. Conquest ideas sound good.

**Comment by Firesoul7** [comment]
As for vanilla group names, I don't think we should change them just for the sake of changing them, but I don't think we should avoid changing either if we have a more fitting name.

**Comment by PhelanBavaria** [comment]
I just think that the player will be more attached to a certain way of doing things. For instance we could have multiple defensive idea groups and everybody can only choose one. Another defensive idea group could be improved fortifications or something.
Indeed "Defensive Ideas" are an all-purpose idea group, but that's where I also see the issue.
Players don't get attached to it because it doesn't say anything about it. Why do I get a bonus for fort defense? "Defensive Mentality" Oh, yeah, that totally explains it...
Whereas for Ambush Ideas it's more descriptive. "Wrecking Supply Trains" Oh, so the soldiers attack their supplies, which causes them to take longer with the siege!

**Comment by qweytr** [comment]
I don't think that is a problem. Vanilla EUIV has had defensive ideas from the beginning and I have never seen anyone bring this up in the forums. If you want to make more specialized idea groups, I guess you could make some with extra triggers for certain regions, cultures or religions, but I don't think doing that should be among our priorities.

**Comment by PhelanBavaria** [comment]
It's by no means a problem. But we are doing something to entertain people and especially to entertain our selves. I would be entertained by being able to imagine what it could mean to pick this certain idea group. Also I would be entertained by picking a defensive idea group more specialized on unit movement than on relying on forts.
Perhaps I should do the ideas by myself to make them consistent, but also taking suggestions from everybody else and convert them if necessary to be consistent.

**Comment by Firesoul7** [comment]
Hmm... But with the example of Ambush ideas, and Improved fortifications, what would be the effects of each? I'm not sure that there are enough effects that can be added to idea groups to make the two distinctive gameplay-wise. Also, talking from experience I haven't read all the descriptions for the different idea groups and their effects. There doesn't seem to be a huge advantage in adding more to me.

**Comment by PhelanBavaria** [comment]
The one would give the player more effects in the direction of attrition for enemies and morale for units, while the other could be cheaper forts, better fortifications and such.
Maybe it wouldn't add anything for you, but it would add something for me and surely for other people.
It's just the way you play the game. Some people pick only big nations, rush it through in speed 5 and cheat, while others enjoy it more to start with a little nation, struggling to rise and enjoy playing in a lower speed to get a better appreciation of how long it actually took to rise.

**Comment by qweytr** [comment]
Defensive ideas could perhaps be divided into Ambush and Fortification if they can be given different enough effects to make them distinct, but I doubt that's possible. Attrition and morale are not enough for an entire idea group and the same goes for just fort defense.

I think we should use the vanilla ideas as a base and change them if there's something to improve. Are there any changes that need to be made to ideas other than defensive? I think that colonization should be made slower, by having exploration only give one colonist and making expansion give the colonist later.

**Comment by Firesoul7** [comment]
I think we should implement province abandonment before we change colonial
idea groups. After all from earlier starts it's possible that some nations
will rely heavily on colonists just to keep their existing land (which is
how I would want it, nations were flimsy things in those times, having to
claw to keep what land they possessed in a lot of cases).

**Comment by qweytr** [comment]
That would perhaps we a good idea, but I also think it would be a good idea to do the changes to the existing idea groups before we start adding new ones.

**Comment by PhelanBavaria** [comment]
I really don't like using the vanilla ideas. I think we should write our own and take inspiration from them.
I'm also not convinced about the usage of colonists because they can be very imbalanced.
We can use the vanilla colonization system, but I would rather initiate them with a decision which starts the colonization process of a nearby province but drains development from other provinces or some other way of simulating moving people from one province to another.
I guess the best thing would be to include colonists and just see what happens.

Still, we need to find an agreement of what we do about the ideas.
What if we agree on that I take the vanilla idea as basis and modify and rename them to fit better in this timeline? Could we all agree on that?

**Comment by Firesoul7** [comment]
It would already be a drain on resources and people to build a colony. The
events to reduce development fire on a province basis, not a country one.
Since each nation only has so many monarch points, building any colony
would endanger and drain your other provinces. The province abandonment
system is supposed to be brutal, putting size limits on all nations
(although certain nations and buildings would make the system a great deal
easier to manage. Having a farm for example would make every development
reducing event around ten times less frequent). Simply put, we don't need
to weaken colonisation.

I can agree with taking the vanilla ideas as basis and modifying and
renaming them to fit.

**Comment by qweytr** [comment]
Depends on how the ideas are modified and renamed. Perhaps you could post your plans here, so we can discuss them in more detail.

**Comment by PhelanBavaria** [comment]
I'm not talking about weakening it, it's just very imbalanced, especially if you don't give everybody a colonist then you can't recolonize your provinces.
Colonizing shouldn't just be as easy as in vanilla, it should be possible, but only occasionally if you have the population do do something like that.

**Comment by PhelanBavaria** [comment]
I don't really have a plan, I wanted to make them like it comes to my mind and constantly grind them, test them how they work out and change them if need be.
I think the best thing to do is that you just let me do the ideas and then we can constantly discuss about needed changes to them.

**Comment by qweytr** [comment]
I guess we can do that.

**Comment by Firesoul7** [comment]
I think colonisation should be possible for everyone. Perhaps we could give
everyone a single base colonist, then change the ideas in the way you
described. I don't think it should be the case that it can only be done if
you have sufficient population. I point out Amarna. Egypt was not in a
position to create such a colony, but it did, and almost completely fell as
a result. That's the situation I want. It should be possible to make
colonies at any point the player chooses, but making a colony at the wrong
point would either result in the fall of the colony or in serious damage to
the state.

**Comment by qweytr** [comment]
No base colonists. There will be plenty of uncolonized land in the earliest starts and nothing would stop them from colonizing half the world.

**Comment by Firesoul7** [comment]
It would be impossible for them to do so. Province abandonment would be so
severe that any given country could maybe make a single successful colony
every century, assuming that they colonise somewhere temperate. If they
colonise a desert, they could expect to never be able to make it
successful, only occasionally keep it as a low development province in
times of high success.

**Comment by PhelanBavaria** [comment]
How you suggest would be a great system, I would be totally down for that if it works.
I have no idea how you would do something like that though, but if you find a good solution, then you have my support.

**Comment by qweytr** [comment]
Seems likely we definitely have to implement the abandonment system before we can consider the colonist situation.

**Comment by Firesoul7** [comment]
Your support is all I need on this. I know what I want, and basically how
it will be done. I'll look into creating a basic system at some point, and
we can then edit that system.

**Comment by Firesoul7** [comment]
OK, but that will result in a lot of nations disappearing completely. It
will seem like the system is too harsh.

**Comment by PhelanBavaria** [comment]
Yes sounds good, but please do it in a way so we can easily remove it again if it's a total failure.

**Comment by qweytr** [comment]
The system needs to be designed so that capitals can't be abandoned. This makes it impossible for countries to disappear entirely.

**Comment by Firesoul7** [comment]
I will make a separate file for province abandonment events. That would
make it easy to remove by nature.

**Comment by Firesoul7** [comment]
I don't agree. I believe nations should be able to fade away completely.
They should be encouraged to sink their monarch points into developing
their capitals to avoid their capitals disappearing in most cases, but a
nation disappearing utterly into the sands is something I believe should be
able to happen.

**Comment by qweytr** [comment]
The number of tags in the early starts is low enough already and the tagcount will decrease anyway as some of them get conquered. I think that allowing countries to vanish entirely would make the game boring rather quickly. Being reduced to just one province is bad enough anyway and would make it easy for neighboring countries to conquer the remains.

It's true though that making the capital immune to abandonment would encourage the player to develop everything but the capital, which isn't a good thing. Perhaps it should instead be made so that the last province of a country can't get abandoned.

**Comment by Firesoul7** [comment]
Most of the Celts have only one province, but by all means some tribes
disappeared. If there is a worry about tag count, maybe we should make more
nations, along with repeatable events which can make nations appear in
empty provinces.

**Comment by qweytr** [comment]
There will need to be event for new countries to appear anyway, but before those are implemented, I think we should not allow tags to disappear. Once those events are in place we can reconsider it. 

And some of the Celtic tribes disappeared because their lands got occupied by others. I don't think there were any provinces in Gaul that were first occupied and later uncolonized.

**Comment by PhelanBavaria** [comment]
Well, there kind of were, especially the provinces along the Danube were victims of reoccurring Germanic raids. This is one of the reasons that most migrations happened from that area.
I will create a migration event now which could take care of that though, so those provinces would be abandoned because they moved to somewhere else.

**Comment by qweytr** [comment]
The Celts left those areas as the Germanic tribes came and those tribes moved elsewhere, meaning that they had other provinces somewhere else to move into. The tribes there didn't just vanish into nothingness.

**Comment by PhelanBavaria** [comment]
That's what I said, except that the Celts didn't move out and the Germans in. There were several waves of them migrating somewhere else before the Germans took over.
The Deserta Boiorum is an example of this.

**Comment by Firesoul7** [comment]
Decolonisation doesn't always mean that a tribe disappeared into
nothingness, just that the tribe lost unity and could no longer be
considered a nation. History is full of such examples. In any event, Celtic
lands are filled with rivers and are highly temperate. Then the Celtic
nations themselves are mostly OPMs who would invest heavily in getting
their capital high development.

**Comment by Firesoul7** [comment]
Specialised ideas were created then removed. Is this issue decided?

**Comment by PhelanBavaria** [comment]
Well, the ideas that I had added were more like drafts. We can close this issue for now and reopen it to a later date, when we all can decide on something.
