### ISSUE TITLE
Additional event pictures

### ISSUE THREAD

**Issue by Firesoul7** [PhelanBavaria/ancienttimeline#38]
The vanilla event pictures are simply not sufficient to cover all of the different things that can happen in events. I believe that we should create some new ones. This is very low priority, but it would be nice to see.

**Comment by qweytr** [comment]
I added a few. These event pictures were created by Adtriarior and I might ask if he could make some more.

**Comment by Firesoul7** [comment]
When did you add them? Where are they? By all means, please tell Adtriarior to make as many as he can please.

**Comment by Firesoul7** [comment]
Excellent, I just saw them. For now what I would like is an event picture showing an abandoned region, and an event picture showing Alexander the Great, maybe holding up a sword, or take inspiration from one of the statues of him,

**Comment by Firesoul7** [comment]
Oh, and will these event pictures be added to ET? They would work great with the Rome Events I did ages ago

**Comment by qweytr** [comment]
The entire event picture pack will be added to ET in the next update. The complete pack contains 20 event pictures, most of which are for later time periods.

**Comment by Firesoul7** [comment]
Sounds great.

**Comment by Firesoul7** [comment]
We're basically aware of this, and I've added a lot of event pictures myself. I don't think that this issue needs to remain open, but if someone disagrees they can reopen it
