### ISSUE TITLE
Animists and Druidists

### ISSUE THREAD

**Issue by Firesoul7** [PhelanBavaria/ancienttimeline#39]
Europe is filled with Animists and Druidists at present. I would like to eliminate the European animists entirely if possible, and split the Druidists at least a bit. There should be at least a Sabellic religion and an Iberian religion added, and I think some others. From what Bavaria has told me not all Celts had Druids, so non-Druidic Celts should have their own religion. I also think that Celtic religions generally should be split into continental, British, and Irish forms, since there were quite a few differences between these groups.

**Comment by qweytr** [comment]
Druidism wasn't an organized religion. The practices were different everywhere. I don't see any way to split it up in any meaningful way. Animism in Vasconia could be replaced with Basque Mythology. https://en.wikipedia.org/wiki/Basque_mythology I have no idea what religion the Iberi would have though.

**Comment by Firesoul7** [comment]
https://en.wikipedia.org/wiki/List_of_Celtic_deities
Turns out that the Celtic religion should be split more than I thought. Britons and Gauls should have the same religion, which I think should be called Druidism, since it is these who are known for the Druids. Technically there should be a separate Welsh religion according to this, but Wales isn't really big enough, and I remember reading something about a Roman army chasing down a big army of Druids in Wales anyway. I think that some Welsh gods and goddesses should be added to Druidism so that they are represented however. Then there should be a Gaelic religion for Ireland, which has Morrighan as one of the goddesses. There's a huge list here though. Finally there should be a Celtiberian religion, which could also just be called Iberian, up to you.

**Comment by qweytr** [comment]
Dividing religions by deities wouldn't work. Most of those were worshipped in only a few provinces and you'd end up having dozens of tiny religions. The thing is, religious matters were not politically significant for the Celts, so splitting Druidism up would serve no gameplay purpose. But let's wait for Bavaria's opinion, as he is apparently the expert on Celtic history.

**Comment by Firesoul7** [comment]
OK, but people who study Celtic religion generally put their deities into
two categories, local and general. While local Gods and goddesses were only
worshipped in a small area, general gods and goddesses could be found
worshipped over large distances. The reason religion wasn't politically
important to the Celts is because there wasn't ever really a case of one
religious group of Celts ruling another religious group, Celtic or no.

**Comment by PhelanBavaria** [comment]
I'm sure not all Celts had druids, the thing is, we simply don't know. The only sources we have are Roman and Hellenic, and we can't trust those sources. For example, perhaps there were Druids in Gaul, but the "Druids" in Britannia were simple priests. I agree with qweytr that splitting them by gods is a bad idea, you would have to split the early Hellenic religion too then.
Splitting the religions by practices seems to be a better way, I think that it's likely that the practices and rituals of the Celts were very similar everywhere with just some mild variations.
I'm not sure if people like the Iberians and Illyrians should get an own religion then. As far as I know the practices there weren't much related.
Also thank you for calling me an expert :)
I think I know as much as you can know about them, which isn't a lot. The rest I just go by my own judgement.

**Comment by Firesoul7** [comment]
OK, then let's have a huge list of gods, and have each culture have access
to certain gods on that list. In any event I want unique Irish gods and
goddesses. It's exactly what I did with Hellenism.

**Comment by PhelanBavaria** [comment]
Early Hellenics didn't have a central believe system either, that's what I meant. There were lots of local gods too which at some point formed this central believe system that we know of.
Celtic gods are much more location based than in most other religions. So if one Celtic tribe migrated to another location, then it was likely that they would stop worshiping their old gods and start worshiping the new. Celtic gods weren't omnipresent, you could almost see them as token for a certain river, a certain valley or even a certain tree or forest.
I think it's very hard to compile a huge list, I think it's fine if we just use the most commonly known ones. That solution might not be very accurate but I think it's the best we got.

**Comment by Firesoul7** [comment]
I'm currently making some gods and goddesses for Irish cultures. Not all
gods were purely local after all. Eriu for example was very important to
everyone in Ireland.

**Comment by PhelanBavaria** [comment]
So you just decide what we do now? Celts are my area to do and you are the only one so far in favor of it.

**Comment by PanzerfaustJoe** [comment]
Lets just stick to our own areas, OK guys?
