### ISSUE TITLE
Auto Conquering and Coring

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#4]
Maybe we should think about some sort of event that transfers an occupied province over to the conqueror (after a certain amount of time) and after a certain amount of time in their possession it will become a core (maybe after a few years).

**Comment by Firesoul7** [comment]
This was essentially my idea, yes. Like the Barbarian migrations but
permanent.

**Comment by qweytr** [comment]
I agree that large conquests need to be made easier. Another way to do this would be to increase administrative efficiency significantly. I don't think coring should be made free, as that would decrease the demand for admin points and the demand is already decreased due to sparser technology.

**Comment by Firesoul7** [comment]
That sounds like the best solution.

**Comment by PhelanBavaria** [comment]
Seems like a sensitive solution to me.

**Comment by Firesoul7** [comment]
We should look through all these issues and determine which can be closed. This hasn't been done yet, has any particular progress on it been done?

**Comment by qweytr** [comment]
I have now increased the administrative efficiency, but I think we should keep this issue open until the system has been tested out.

**Comment by PanzerfaustJoe** [comment]
I was checking out the death of Alexander event, and I like how it gives provinces to the successors. I think that eventually one of the successors should be able to reform Macedon if he controls certain important provinces of Alexander's Empire. Kind of like reuniting the fractured kingdoms.

Just a thought

**Comment by Firesoul7** [comment]
Already implemented. Whoever controls the kingdom of Macedon at the end of the Diadochi wars can reform Macedon.

**Comment by PanzerfaustJoe** [comment]
When Alexander is conquerring provinces you should gain a small amount of prestige, gold, legitamacy, and monarch points in each category to reflect his quic successful conquest of an empire twenty times his size.

**Comment by PanzerfaustJoe** [comment]
Also cant you just have an event that lowers coring cost for a hundred or so years?

**Comment by Firesoul7** [comment]
Can we close this?

**Comment by qweytr** [comment]
Closed.
