### ISSUE TITLE
Order of the Dev team

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#40]
So I thought that it would work if nothing is overly well defined and we kind of just work on this project.
It appears to me that that's not the case though, so I will define how it'll work.

Everyone has their areas to work on, those areas are defined by culture rather than by provinces.
So here the definition of who does which area:
Celts, Iberians and Thracians/Dacians: PhelanBavaria
Greeks and Middle Eastern: firesoul
Italics and Illyrians: fangwolf4
Africans: Joe
Far  Eastern: qweytr (apparently)
Steppe people: Unassigned
Americas: Unassigned

Additionally there is work which covers multiple cultures, such as religions and events.
For those I would suggest that everybody just does those things as they come to mind.
If you add a new religion or a new event/decision or others, then inform the person who is culturally involved in that.

EVERY thing added to the mod can be questioned. If you don't like what somebody else did, write an issue and we'll discuss it. Generally speaking the majority vote on an issue should win, but qweytr and I as project leaders have a veto which we will only use if we think that a change would offset the mod (but usually you all are very reasonable people, so I don't think that we will ever use that).

NOTHING will be edited outside your cultural area, except if you asked the person responsible for it.
If a region is considered done (when the milestone is done) qweytr and I will be able to make bugfixes on them and little changes. You are allowed to create issues on those changes too if you don't agree with them.

I will close this issue as soon as everybody replied to it and agrees with it.

**Comment by qweytr** [comment]
I'm fine with this for now. But at some point closer to release I will have to be able to make changes to any region freely. It would simply be too time consuming to ask for a permission for every single bugfix. Basically I suggest that each of us can only work on their own area until the person working on that area thinks he's done with it, but once he thinks the region is finished, other people can make fixes or add content like events there. I also consider myself having veto power over any decisions.

I consider myself done with India. I'm not going to make any events for e.g. the rise of the Maurya or anything else. If you think this would be necessary, you can add those yourself.

China is done as well apart from rulers. I'm not going to add any events there either, so if you think some are needed, you can add them.

**Comment by PhelanBavaria** [comment]
That sounds good, I'm adding that.

**Comment by Firesoul7** [comment]
Well, excepting units I would consider Greece and the Middle East done for the current milestone, although a lot more will still need doing for earlier and later dates.

**Comment by PanzerfaustJoe** [comment]
Good to hear this. I agree with qweytr too, for after the release because it will be a pain for him to try and get into contact with one of us whenever he wants to make a small change. 

Hopefully things can become a little more orderly now, not that they weren't at all before.

**Comment by fangwolf4** [comment]
Firstly, my areas weren't even started in terms of overall progression because of that it will take more time to finish.
Secondly,I think that Joe and qweytr have a good point.
Thirdly,I'll probably come up and make events for my areas as I go.
and Finally,thanks for adding me,I'll do my best and be able to finish my area quickly, so I'll catch up with the rest of the team

**Comment by qweytr** [comment]
Far East is now done as far as I'm concerned and I'll probably start working on the steppes next if no one else want to.

**Comment by Firesoul7** [comment]
Is this issue closed now?

**Comment by Firesoul7** [comment]
I'm going to close this, being as a lot of this isn't even valid any more.
