### ISSUE TITLE
AI very stupid about Alex' conquest of Persia

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#41]
The AI never conquers the Achaemenids, the only time I saw them was in a defensive war where they helped Bythinia.
My proposal would be to force them by event to declare war, but only if the AI plays as MCD.
If you can find a better solution then do that.

**Comment by Firesoul7** [comment]
This solution seems best.

**Comment by qweytr** [comment]
Another problem is that when Macedon declares war, it usually peaces out way too soon. I think this problem is mainly caused by the instant annexation system.

**Comment by Firesoul7** [comment]
Not having that system would only make it worse. A possible way to fix the
problem might be to set up a repeating event that keeps Alexander at war
with the Achaemenids for as long as he lives, or until one of them no
longer exists.

**Comment by qweytr** [comment]
That wouldn't work. And I'm not suggesting to get rid of the annexation system entirely, but there should be a delay between the province occupation and the annexation like in ET.

**Comment by qweytr** [comment]
Another way to make Macedon more interested in conquering Persia would be to grant them claims on all Achaemenid provinces.

**Comment by Firesoul7** [comment]
Possibly

**Comment by Firesoul7** [comment]
Can this be closed? Was it ever fixed?

**Comment by qweytr** [comment]
This has not been fixed and I don't think it can be fixed. The reason the AI fails to conquer all of Persia is not because it can't, it's because it doesn't want to. If you take a look at the provinces AI Macedon desires, it has no interest in most Persian provinces.

**Comment by Firesoul7** [comment]
Can we close this issue then as a 'as good as we'll get'?

**Comment by qweytr** [comment]
I can close this for now. I'm not happy with how the AI Macedon behaves, but for now there are more important things to deal with.
