### ISSUE TITLE
Macedon splits even if they are tiny.

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#42]
We have to discuss if this is an issue or not.
My opinion is that is it, most of the times when kingdoms or empires split between successors it was because they were big.
A little Macedon would probably not split, so the event of splitting should be adjusted, based on cities.

**Comment by Firesoul7** [comment]
Sure, but I didn't think this was a priority for this release. I'd prefer
to finish development etc first

**Comment by PhelanBavaria** [comment]
I honestly don't think it's much work to do. If you want me to do it then I will.

**Comment by Firesoul7** [comment]
I'd rather do it myself, I won't be able to work on it for a while, but in
that time I'll be getting a very strong vision of what I want.

**Comment by qweytr** [comment]
It was agreed that the number of the successor kingdoms will depend on the number of provinces Macedon has. I agree that this feature should be in the first release.

**Comment by Firesoul7** [comment]
Did it.
