### ISSUE TITLE
Development for provinces across the world

### ISSUE THREAD

**Issue by Firesoul7** [PhelanBavaria/ancienttimeline#43]
Mainly in Greece and Achaemenid Empire for this release, other regions can be worked on later.

**Comment by Firesoul7** [comment]
My part of this is finished. Is everyone else happy to consider this issue completed for the current milestone?

**Comment by qweytr** [comment]
The development is done for all of my regions as well.

**Comment by PhelanBavaria** [comment]
Mine is mostly done, but since it isn't relevant for this release, you can close the issue (I think)

**Comment by PanzerfaustJoe** [comment]
North Africa is done

**Comment by qweytr** [comment]
I'll close this one then.
