### ISSUE TITLE
Religion mechanics

### ISSUE THREAD

**Issue by qweytr** [PhelanBavaria/ancienttimeline#45]
Many of the new religions will be using the deity mechanism, which is fine, but with many of the vanilla religions gone there are plenty of other mechanisms that could be relocalized into something useful.

Currently, the following mechanisms are unused by this mod:
- Muslim piety.
- Orthodox Patriarch authority
- Catholic Papal system
- Protestant church aspects
- Reformed fervor

I think that these mechanics could be great in making the new religions more interesting, but I don't have any good ideas on which religions to add these mechanics to.

**Comment by Firesoul7** [comment]
I'm guessing that a religion can't have both deities and one of those other
mechanisms? That eliminates most of them, although perhaps Patriarch
authority could be used for Seraphis.

**Comment by qweytr** [comment]
It's not possible to use several mechanics for one religion as far as I know.

**Comment by PhelanBavaria** [comment]
That's a great idea!
I'm not too familiar with most of these actually, but the Muslim piety system may be used for Zoroastrians?
I think the others might only find a use for possible reformed religions, if we are going to implement those.

**Comment by fangwolf4** [comment]
Zoroastrian don't have something resembling piety,closest thing for Zoroastrian is fervor or authority

**Comment by Firesoul7** [comment]
I'm not sure any of these mechanics could be used for Zoroastrianism.

**Comment by qweytr** [comment]
Remember that anything can be relocalized into anything else. The piety slider could for example be turned to simulate the struggle between Ahura Mazda and Angra Mainyu or to differentiate the panentheistic and pantheistic approaches to Zoroastrianism.

**Comment by PhelanBavaria** [comment]
I think we could even replace the images used for these sliders if need be. I'm not very educated on the Zoroastrians though, just know the basics.
the papal system could be used for reformed Druidists, it appears that they went more and more centralized with their religious centers, so it could have been a possibility that they would have established one center of religion at some point and adapted a similar system to the Papacy.

**Comment by qweytr** [comment]
I'm not so sure about using the papacy for Celts. Of course we can't know what a reformed Druidic religion would have been like, but there's little historical support for a single head of religion accepted by all Celts. A system like patriarch authority would make more sense with different countries having different druids as their head of religion.

**Comment by PhelanBavaria** [comment]
Hum, that actually sounds pretty good. As I said, I don't know how most of these systems work, but I agree with you if it's like that.

**Comment by PhelanBavaria** [comment]
One thing that just came to my mind, what if you want to convert your savegame to ET?
You can't use the same system for papacy and for whoever we want to use that system for at the same time.

**Comment by PanzerfaustJoe** [comment]
While we are not sure at this point about a converter, we should act as if it were a fact and leave in things that may need to be a part of it.

**Comment by qweytr** [comment]
Of course if any of these mechanics are used for the new religions in this mod, the religion will lose that mechanic when the save in converted to ET.

**Comment by Firesoul7** [comment]
When you say 'the religion', do you mean the ET religion or the AT religion? Either way, can we consider this issue closed?

**Comment by qweytr** [comment]
I guess this can be closed. Any remaining questions can be discussed in another issue.
