### ISSUE TITLE
Macrones

### ISSUE THREAD

**Issue by PanzerfaustJoe** [PhelanBavaria/ancienttimeline#46]
In earliest few hundred years, I found a tribes which you could add to a province in Anatolia that Rome still controls. 

https://en.wikipedia.org/wiki/Macrones

They would probably control Trebizond or Canik. Just a suggestion.

**Comment by qweytr** [comment]
As far as I know those areas were under Persian control until Alexander's conquest. There's no need for an additional tag there.

**Comment by PanzerfaustJoe** [comment]
Oh OK, I only mentioned because Rome controlled it.
