### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by qweytr** [PhelanBavaria/ancienttimeline#48]
For the first release there needs to be several units for each tech group. There should be at least five levels of infantry and four levels of cavalry for each group. Here's a list of units done so far:

Balkan
Inf 1: Peltast
Inf 2: Elite Peltast
Inf 3: Falxmen, Rhomphaia Warriors
Inf 4: Hellenized Infantry
Inf 5: Noble Infantry
Cav 1: Light Cavalry
Cav 2: Scythian Cavalry
Cav 3: Royal Cavalry

Celtic
Inf 1: Longswordsmen
Inf 2: Shortswordsmen
Inf 3: Spearmen
Inf 4: Ambaxtoi
Inf 5: Celtic Phalanx
Cav 1: Chariot
Cav 2: Trimarcisia, Elite Chariot
Cav 3: Chariot Javelineers
Cav 4: Mounted Skirmisher

Mediterranean
Inf 1: Phalanx, Peltast
Inf 2: Elite Phalanx
Inf 3: Thureophoi
Inf 4: Hastati, Principes
Inf 5: Legionaries
Cav 1: Companion Cavalry
Cav 2: Heavy Companion Cavalry
Cav 3: Equites

Middle Eastern
Inf 1: Immortals, Sparabara
Inf 2: Middle Eastern Phalanx, Bedouin Warriors
Inf 3: Argyraspides, Javelineers
Inf 4: Chrysaspides, Hillmen
Inf 5: Romanized Infantry, Reflex Bowmen
Cav 1: Scythe Chariot
Cav 2: Cataphract, War Elephant
Cav 3: Elite Cataphract
Cav 4: Partian Shot

Chinese
Inf 1: Crossbowmen
Inf 2: Bronze Swordsmen, Heavy Crossbowmen
Inf 3: Iron Swordsmen
Inf 4: Chinese Conscripts
Inf 5: Chinese Volunteers, Chinese Militia
Cav 1: Chariots
Cav 2: Chinese Horsemen
Cav 3: Nomadic Cavalry

Scythian
Inf 1: Tribal Warriors
Inf 2: Steppe Archers, Steppe Spearmen
Inf 3: Heavy Steppe Spearmen
Inf 4: Foot Skirmishers
Inf 5: Royal Guards
Cav 1: Skirmishers
Cav 2: Horse Archers
Cav 3: Elite Horse Archers
Cav 4: Steppe Raiders

Indian
Inf 1: Longbowmen
Inf 2: Swordsmen
Inf 3: Spearmen
Inf 4: Elite Longbowmen
Inf 5: Steel Bow
Cav 1: War Elephants, Chariot
Cav 2: Elephant Archers
Cav 3: Armored Elephant, Asvakas
Cav 4: Elephant Sword, Heavy Cavalry

Nomad
Inf 1: Nomadic Bowmen
Inf 2: Nomadic Levy
Inf 3: Steppe Fighters
Inf 4: Dismounted Raiders
Cav 1: Steppe Horsemen
Cav 2: Steppe Raiders
Cav 3: Horse Archers
Cav 4: Steppe Horde

North African
Inf 1: Sacred Band
Inf 2: Libyan Skirmishers
Inf 3: Libyan Spearmen
Inf 4: Assegai Warriors
Inf 5: Berber Spearmen
Cav 1: Mounted Javelineers
Cav 2: Numidian Cavalry
Cav 3: War Elephants, Numidian Raiders
Cav 4: Armored Elephants

If you have any ideas for new units, post them here.

**Comment by qweytr** [comment]
I can't find enough units for the Balkan group. I none of you can find some more units then I will make them use the mediterranean ones.

**Comment by Firesoul7** [comment]
Peltast should be moved to the second Balkan slot, with 'Thracian Javelinmen' in the first. What we think of when we picture a Peltast was not the first iteration of the troop. 'Sica Fighter' could be added, since the sica was considered their national weapon. All Thracians were renowned for their cavalry, I think the first cavalry slot should be 'Thracian Cavalry' and the second 'Odrysian Cavalry'. 'Rhomphaia Warrior' and 'Falxmen' could go in the fourth infantry slot. The final infantry slot could be 'Thracian Nobles'. The third cavalry slot could be 'Hellenised Cavalry'. 'Thracian Royal Cavalry' would be the final cavalry slot.

**Comment by Firesoul7** [comment]
By the way, I think the Chinese troop types should mention their traditional weapons of Ji, Jian, and others.

**Comment by Firesoul7** [comment]
Scythian
Inf 1: Young Axes, Tribesmen
Inf 2: Steppe Archers, Steppe Spearmen
Inf 3: Heavy Steppe Spearmen
Inf 4: Foot Skirmishers
Inf 5: Royal Guards
Cav 1: Horse Archers, Amazonian Warriors
Cav 2: Scythian Chariot, Armored Mounted Archers
Cav 3: Skirmishers, Noblewomen
Cav 4: Steppe Lancers, Raiders

**Comment by qweytr** [comment]
Thank you. I removed the ahistorical Amazon units and it seems that chariots were no longer used in Scythia at that time. I have added a modified list to the first post.

**Comment by Firesoul7** [comment]
There were 'amazons' among the Scythians, in fact the Scythians were the
inspiration for Greek amazons. Scythian women fought on the battlefield
alongside their men all the time, in fact most nomadic societies had very
good gender equality.

**Comment by qweytr** [comment]
It's likely that there were some women in the Scythian armies, but that's something to include in the unit descriptions rather than the names. Amazons didn't exist in the way they are generally understood in western cultures.

**Comment by Firesoul7** [comment]
Balkan:
Cav 2: Thracian Cavalry
Cav 3: Hellenised Cavalry

Mediterranean:
Cav 4: Elite Equites

Chinese:
Cav 4: Chinese Cataphracts (Google them, they were used between the Jin and the Tang, which is a little late but technology wasn't advancing so much so they could have got them early, or alternatively these could be seen as an earlier version of the troop)

**Comment by qweytr** [comment]
I was thinking that not all groups need the fourth cavalry unit. The Roman cavalry for example was quite a lot behind the Persian one and the Chinese had worse cavalry than the nomads to their north. Especially if there aren't any better ideas than elite variants and units out of the timeline. 

Indian and Nomad groups are the big ones that are still undone. It might also be good to have a separate group for Germanic peoples and perhaps North Africans.

**Comment by Firesoul7** [comment]
I'm always in favor of more unit groups, please add them to the main post. Also, what about the Balkan group? Is there anything wrong with my ideas for their cavalry? Also, which unit groups are yet to be implemented in the mod? Perhaps some sort of symbol or something after implemented unit groups?

**Comment by Firesoul7** [comment]
Since we already have Phalanx for Infantry 2, maybe we could have Thorax Pikemen for one of the Middle Eastern Infantry Slots. Hillmen for another, and maybe Persian Javelins.

**Comment by Firesoul7** [comment]
Possibly Bedouin Warriors, they had a fierce reputation even in those times.

**Comment by Firesoul7** [comment]
Hmm, perhaps we could have Babylonian bowmen for the first infantry slot, and move everything else up one. Bedouin Warriors would then go in the Third slot with the Phalanx, and Thorax Pikemen with Hillmen for the fourth slot. The final infantry slot could be Persian Javelins.

**Comment by Firesoul7** [comment]
Middle Eastern
 Inf 1: Babylonian Bowmen
 Inf 2: Immortals, Sparabara
 Inf 3: Middle Eastern Phalanx, Bedouin Warriors
 Inf 4: Thorax Pikemen, Hillmen
 Inf 5: Persian Javelins

**Comment by Firesoul7** [comment]
I think this group should be quite diverse, including all those that I mentioned, since the Middle Eastern group in reality reflects an extremely diverse group of civilisations.

**Comment by qweytr** [comment]
I'm not a fan of Thracian Cavalry. I generally try to avoid naming units according to peoples or locations.

I don't remember exactly which units are in and which are not. I guess this means that some sort of indication would be useful.

The first infantry slot is the one you have at the start during Alexander's invasion. Persians fought Alexander with Immortals and Sparabara, so I think they should stay in in the first slot.

**Comment by Firesoul7** [comment]
OK, but what troops will be used pre-Alexander?

**Comment by qweytr** [comment]
We'll worry about that once we get there. For the first release it's Alexander and after.

**Comment by Firesoul7** [comment]
Middle Eastern
 Inf 1: Immortals, Sparabara
 Inf 2: Ashum, Bedouin Warriors
 Inf 3: Middle Eastern Phalanx, Argyraspides
 Inf 4: Thorax Pikemen, Hillmen
 Inf 5: Persian Javelins, Chrysaspides, Chalkaspides

**Comment by Firesoul7** [comment]
There

**Comment by qweytr** [comment]
What are Ashum, Khahyahlim, Shotelai, Thorax Pikemen and Sahnegohrim?

**Comment by qweytr** [comment]
Remember that the biggest Middle Eastern countries during the period were Achaemenids, Seleucids and Parthia, so the units should be designed to fit them.

**Comment by Firesoul7** [comment]
Ashum are Arabian archers, Khahyahlim and Sahnegohrim are both Jewish, but were used as mercenaries all over. Shotelai is a warrior that uses a Shotel, a curved blade, they were common all over the place. Thorax Pikemen were originally pikemen with very long spears used by Alexander, but his successors all used them too.

**Comment by Firesoul7** [comment]
Ashum were used as mercenaries by Seleucids and Parthians, probably Achaemenids too. Same deal with the Jewish troops. Shotelai were used by absolutely everyone, and Thorax Pikemen were used by Seleucids and Parthia. It's likely had the Achaemenids survived they would have adopted them too, because they were so effective.

**Comment by Firesoul7** [comment]
Any of those units can be used by any of the big powers of the Middle Eastern group, but without including diversity many of the smaller powers may find themselves with weird units.

**Comment by qweytr** [comment]
According to Wikipedia Shotel was used only by one country, Damot, during this period. The others I can't find anything on, so you need to show some sources before I can add them.

**Comment by Firesoul7** [comment]
OK, it seems that I thought Shotel was a more generic name than it is, Shamshir Warriors can be used instead.

**Comment by qweytr** [comment]
Seleucids should perhaps use Mediterranean units, so we don't need to add Greek units to the Middle Eastern set.

**Comment by Firesoul7** [comment]
The Jewish ones come straight from here: http://www.honga.net/totalwar/attila/unit.php?l=en&v=attila&f=att_fact_himyar&u=att_des_es_sahnegohrim
http://www.honga.net/totalwar/attila/unit.php?l=en&v=attila&f=att_fact_himyar&u=att_des_es_khahyahlim

**Comment by Firesoul7** [comment]
Then you would also have to make Parthia use the Mediterranean group, and add a bunch of Persian units to the Mediterranean set. The simple reality was that Persian powers started to use some Greek units. They didn't have the same kinds of standing armies as say the Romans, and so they weren't that nationalist about what units they used, it was just, what can we get that's good.

**Comment by Firesoul7** [comment]
http://www.honga.net/totalwar/attila/unit.php?l=en&v=attila&f=att_fact_himyar&u=att_des_es_ashum
http://www.honga.net/totalwar/rome2/unit.php?l=en&v=rome2&f=rom_ptolemaics&u=Gre_Thorax_Pike
Here's where Ashum and Thorax Pikemen are from, I rely on stuff like this quite a bit, but there's absolutely no other source of unit names, and who is complaining about Total War's research?

**Comment by qweytr** [comment]
Those are Jewish Himyarite units. Judaism didn't spread there until long after the end of this mod's timeline and Himyar wasn't that relevant yet either. The most important Yemeni state during the timeline was Sabaea.

**Comment by Firesoul7** [comment]
They are used by Himyar, and they are Jewish, but who says that other groups didn't use them. It wasn't just luck that caused the Jews to survive so long, it was how good they were at fighting.

**Comment by qweytr** [comment]
I'm not saying they didn't use them, but if there are no sources saying they did I can't add them.

**Comment by Firesoul7** [comment]
I've removed them now. What about the other units?

**Comment by qweytr** [comment]
You suggested Shamshir Warriors. This worn't work either, as Shamshir was introduced to Persia in the 9th century AD.

**Comment by qweytr** [comment]
The Seleucids are a bit troublesome, as they used Greek infantry and Persian cavalry, mainly Phalanx and Cataphracts. It would be quite easy to fill the Middle Eastern set with Seleucid units like Argyraspides, Chrysaspides and Chalkaspides. Later on the Seleucid infantry was Romanized, so Romanized infantry could be in there as well.

**Comment by Firesoul7** [comment]
As long as the Middle Eastern set has plenty of troops that aren't called 'Persian sword guy', then I'm happy. 


Sent from my Samsung device

-------- Original message --------

**Comment by Firesoul7** [comment]
North African:
Inf 1: Desert Tribesmen
Inf 2: Libyan Spearmen, Punic Nobles
Inf 3: Nubian Archers, Assegai Spears
Inf 4: Tuareg Warriors, Aures Mountain Fighters
Inf 5: Azamigh Spearmen
Cav 1: Camel Riders
Cav 2: Nubian Camels
Cav 3: Elephant Riders
Cav 4: (Armoured) War Elephants

**Comment by Firesoul7** [comment]
Nomad
 Inf 1: Nomadic Bowmen
 Inf 2: Nomadic Levy
 Inf 3: Steppe Fighters
 Inf 4: Dismounted Raiders

**Comment by Firesoul7** [comment]
For Indian cavalry: http://theindianhistory.org/Gupta/gupta-empire-military.html this describes a successor but says that traditionally chariots were used. The Gupta Empire changed to mounted cavalry, I'll try to find something on earlier nations so we have something direct though.

**Comment by Firesoul7** [comment]
https://en.wikipedia.org/wiki/Nanda_Empire#Military This is all I can get, no specific names, it seems they used both cavalry and chariots

**Comment by Firesoul7** [comment]
I think the first cavalry slot should be Chariots, they can have both chariots and war elephants in that slot.

**Comment by Firesoul7** [comment]
https://en.wikipedia.org/wiki/Military_history_of_India

**Comment by Firesoul7** [comment]
OK, Spear Cavalry, Bamboo Longbows and Khanda Swordsmen were all used under the Mauryas. Nanda can have Bengali Warriors, since it was with those that they conquered India. We can also have 'Indian Spears', which would describe 'Other foot soldiers could be armed with a large animal hide tower shield and a spear or javelins' from the article.

**Comment by qweytr** [comment]
All the suggested units are now done, so I consider the units done for the first release. New units can be discussed later in a new issue if necessary.
