### ISSUE TITLE
Colaboration with mod "Imperium Universalis"

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#52]
Imperium Universalis is a mod also set during the Ancient times. Their map doesn't represent the whole world however, so I don't think that we are at direct rivalry to them.
I didn't want to approach them without having your guy's approval, so what do you think?
Should we collaborate with them?

**Comment by Firesoul7** [comment]
I don't think so, I think that would limit us and undermine the project.
Their focus is Rome, and anything before Rome seems to be ignored. Also the
quality of their research is not high.

**Comment by Science-Recon** [comment]
I haven't really seen much, I'm looking at it now.

**Comment by Firesoul7** [comment]
They seem to ignore anything outside of Greecaly

**Comment by PhelanBavaria** [comment]
I agree with the research part... But they have some nice events, balance stuff and they also want to create unit models. I think we could benefit from each other.

**Comment by Science-Recon** [comment]
How would collaboration work? Would we somehow merge the two things together or move to them completely, or are you just suggesting we swap certain code? (Events/art/stuff)

**Comment by Firesoul7** [comment]
I wouldn't be opposed to use of some of their events and models, but I
don't see what they would gain from the bargain, and I wouldn't want to
compromise our high quality of research to things that are only partly
thought out and possibly highly inaccurate.

**Comment by qweytr** [comment]
Collaboration is a good thing. If that mod has some events or other stuff that could be useful in this mod, feel free to ask them for permission.

**Comment by PhelanBavaria** [comment]
Alright, I added the main developer as friend on Steam, let's see what he'll say.
What I meant by collaboration is that we exchange things that are useful. We can help them with history while they can give us events, help with balancing, units and who knows what else.

**Comment by Firesoul7** [comment]
That would work.

**Comment by PanzerfaustJoe** [comment]
Eh, I don't know if I agree with this, but if that is what everyone else wants.

**Comment by Firesoul7** [comment]
Turns out the Imperium guy doesn't want to colab with us anyway

**Comment by PhelanBavaria** [comment]
Well, it doesn't seem like they want to. I think we should just look at their mod and get inspirations from it. If there is something they do better than we do, then we can try to copy it or make it even better.
