### ISSUE TITLE
Institutions

### ISSUE THREAD

**Issue by qweytr** [PhelanBavaria/ancienttimeline#54]
With Right of Man being released soon it's time to start thinking about what institutions should be added in AT. 

Here are the institutions we will be using:
Agriculture (at start)
Writing (3000BC)
Bronzeworking (2800BC)
Taxation (2600BC)
Domestication (2400BC)
Pantheon (2200BC)
Laws (2000BC)
Ard Plough (1900BC)
Irrigation (1800BC)
Calendar (1700BC)
Astrology (1600BC)
Caste System (1500BC)
Literature (1400BC)
Trade Networks (1300BC)
Ironworking (1200BC)
Crop Rotation (1100BC)
Animal Husbandry (1000BC)
Craftsmanship (900BC)
Architecture (800BC)
Mathematics (700BC)
Philosophy (600BC)
Medicine (500BC)
Steelworking (400BC)
Theatre (300BC)
Astronomy (200BC)
Ancient Imperialism (100BC)
Legalism (1AD)

**Comment by Science-Recon** [comment]
So.
The first institution should probably be agriculture, as that's kinda like the feudal institution in the base game. Writing would be another one, whether you'd split that into different developments in writing (We do have A LOT of time.) I'm not sure. Bronze/iron/steelworking seems like another good one. Theatre could be another. Maybe something about government? Like Athenian democracy?

As for bonuses and triggers, I'm not sure what bonuses you'd have for agriculture, as population isn't really a thing in EUIV. Manpower or forcelimit maybe?  For spawning, it'd be the gamestart one in Egypt. Writing could be idea and/or tech cost reduction. Could spawn in Mesopotamia, somewhere dependent on trade or maybe someone that has different cultures/neighbours with different culture. Bronze/Iron/Steelworking could maybe have combat ability modifier? Or shock, since that's apparently an idea now. Spawning could be any civilised nation that has the respective material as a tradegood. Theatre could be a Greek culture/area thing, like the Renaissance in the base game. That could be a culture conversion cost reduction? Unrest reduction?

Anyway, that's just some ideas I have.

**Comment by Firesoul7** [comment]
I don't agree with Athenian democracy, since it was only practiced in Athens, and institutions should ultimately be adopted by the whole world.

**Comment by qweytr** [comment]
Agriculture works great as the starting institution.

Writing could be split into Writing and Alphabet.

Bronze-, Iron- and Steelworking could all be added.

Theatre is a good one as well, but the institutions shouldn't be tied to regions. While Greece was advanced historically, it might not end up so if you start in 3000BC. Democracy in general feels a bit off, as most countries at the time were monarchies and it would be weird for them to embrace democracy.

**Comment by Firesoul7** [comment]
Making Alphabet into an institution is rather anti-Chinese. It could perhaps be split into Divining (the purpose of most early scripts) and full Writing.

**Comment by Science-Recon** [comment]
For Writing, we could have Ideography, and then Phonology? As for Athenian democracy, yea, that's probably not the best idea.

**Comment by qweytr** [comment]
I know alphabet isn't optimal for all parts of the world, but the timeline to cover is very long and even with a rather long interval for new institutions we still need a huge number of them, so all of them will probably not fit the entire world perfectly. I'd say we shouldn't be too strict about what is a fitting institution and if we get plenty of ideas we can then scrap some of the less fitting ones.

**Comment by Firesoul7** [comment]
Phonology includes the Arabs, but doesn't help with the Chinese much. While many Chinese characters contain hints as to their sounds, not all do. The 'Phonology' institution could maybe be called 'Logograms and Phonograms'. This would not only avoid the idea of the Chinese being somehow more 'primitive', but would also include the Egyptians and Mesopotamians.

They could even be called Proto-writing and Writing. Proto-writing is really old though.

**Comment by Firesoul7** [comment]
One must consider that for the entire timeline alphabetic systems are limited to the Phoenicians, the Greeks, and the Latins/Etruscans

**Comment by Science-Recon** [comment]
Phonology could represent the use of Rebus and such in Chinese.

**Comment by Science-Recon** [comment]
Some sort of medicine could be a good institution. As could philosophy.

**Comment by qweytr** [comment]
If alphabet is too specific it could perhaps be called something like "Advanced Writing System" 

Medicine is good. Philosophy is as well, though it is a bit broad and could perhaps be divided into things like Ethics and Epistemology.

**Comment by Science-Recon** [comment]
Alphabet is restrictive, but something like Phonology or Rebus should be ok. What does Firesoul think?

**Comment by Firesoul7** [comment]
If it were 'phonology and rebus' I would agree, but rebus doesn't work for alphabets, abjads, or syllabaries, and phonology doesn't work for Chinese, Egyptian, Mesopotamian, etc. Advanced Writing System is also workable, but if it can be so long I don't see any problem with 'Phonology and Rebus' either. Cultures would typically prefer one, but might use the other for niche things.

**Comment by Science-Recon** [comment]
Yea, phonology and rebus sounds fine.

**Comment by Science-Recon** [comment]
Does anyone know exactly how natives work in the patch? Are they determined by tech group, tech penalty or Institutions or any/all of those?

**Comment by Firesoul7** [comment]
Tech group I believe, which is unfortunately just as grating on the nerves.

I've been reading about the Aztecs, who made extensive use of canoes to transport goods and people over large parts of the empire, these systems, and especially the canals of Tenochtitlan, were famous. The Caribs and Arawaks meanwhile colonised the whole Caribbean, and 'primitive' Taiwanese who don't even get a country ingame (fair enough, they were ultra-tribal) managed to colonise the whole of Polynesia, as far as Hawai'i, and yet all of these nations need the helping hand of a 'benevolent' European overlord to establish colonies across 2 kilometers of water or to form an empire of any real power? It infuriates me, it ranks, along with the bizarre new vanilla culture groups, as among the worst decisions ever made by Paradox. How they can accept such insulting colonial revisionism without a second thought...

**Comment by Science-Recon** [comment]
Hmm... The define 'NDefines.NCountry.PRIMITIVES_TECH_MODIFIER' is gone, and I can't find anything to replace it. In addition, the reform government button in vanilla now says that you need to be next to a country that has embraced an institution. This seems to imply that natives can't have institutions? Because the British celts were at ironworking at the time of Alexander until the enddate.

**Comment by Firesoul7** [comment]
What's happening at the moment? Are more institutions needed for initial release? We're not so far from finishing now, but we need to update for the next game version

**Comment by Firesoul7** [comment]
Mathematics could be put at 700, https://en.wikipedia.org/wiki/Mathematics#History Greek mathematics started a century later, advanced mathematics was already being done by Egyptians and Babylonians over 1000 years before that, so we could put Mathematics at 700 to call it the point where Maths was really spreading

**Comment by Firesoul7** [comment]
Irrigation (1500BC)
Crop Rotation (1100BC)
Animal Husbandry (1000BC)
Mercenaries (900BC)
Architecture (800BC)
Mathematics (700BC)
Steelworking can be moved to 400BC

**Comment by Firesoul7** [comment]
Full:
Agriculture (at start)
Writing (3000BC)
Bronzeworking (2800BC)
Taxation (2500BC)
State Religion (2200BC)
Laws (2000BC)
Astrology (1800BC)
Irrigation (1500BC)
Literature (1400BC)
Diplomacy (1300BC)
Ironworking (1200BC)
Crop Rotation (1100BC)
Animal Husbandry (1000BC)
Mercenaries (900BC)
Architecture (800BC)
Matematics (700BC)
Philosophy (600BC)
Medicine (500BC)
Steelworking (400BC)
Theatre (300BC)
Astronomy (150BC)
Legalism (100BC)
Ancient Imperialism (100BC)

**Comment by qweytr** [comment]
The list of institutions is now complete. I'll keep this open until they have been added to the mod and before that happens you are free to post any suggestions for changing the list.

**Comment by PanzerfaustJoe** [comment]
Nothing from me, looks good as is/

**Comment by qweytr** [comment]
I have now started implementing the institutions. It would be helpful if any of you could add in the lines in localisation/at_institutions_l_english.yml that are marked with (to-do) while I work on the more technical aspects of the institutions.

**Comment by PanzerfaustJoe** [comment]
Hey sorry I havent worked on AT much, been super busy IRL, I will try to work on it this weekend.

**Comment by Firesoul7** [comment]
Since these were implemented, can this issue be closed?

**Comment by qweytr** [comment]
Yes, this can be closed. If there are additional suggestions regarding this you can open another issue.
