### ISSUE TITLE
Buddhism

### ISSUE THREAD

**Issue by Firesoul7** [PhelanBavaria/ancienttimeline#8]
At present there is a united Buddhist religion ingame. This not only creates an inaccuracy, as Mahayana provinces are now considered no_religion, but also is unhistorical. While Vajrahana had not yet appeared, Theravada and Mahayana were already separate quite a while before the end of this timeline. I think Buddhism should be re-split.

**Comment by qweytr** [comment]
Sure. The original religion file I made was just a rough draft and was by no means meant to represent anything final.

**Comment by PhelanBavaria** [comment]
I guess this issue is closed?
This was just a proposal, so if you want to make sure that we don't forget about the task, you can open another issue.

**Comment by Firesoul7** [comment]
I guess.
