### ISSUE TITLE
Restricted Discoveries

### ISSUE THREAD

**Issue by PhelanBavaria** [PhelanBavaria/ancienttimeline#9]
People back then didn't know how the entirety of Europe looked like.
Most nations probably only knew who their direct neighbors were, except for a few such as Carthage, who had trade networks reaching even up to Britain.
The proposal is that every tech group should only see every other nation inside that tech group (for some exceptions like Carthage who know their way to Britain).
Also I propose that every nation gets access to explorers (maybe by policy).

**Comment by Firesoul7** [comment]
Hmm... I think it shouldn't be that simple. Take Alexander and the
Achaemenids. If this idea were implemented as is then Alexander would be
entirely unaware of the Achaemenid's existence. I agree with giving
explorers to all nations, but I think a better system is needed than simple
tech groups.

**Comment by PhelanBavaria** [comment]
Well, I'm not sure if Alexander really knew the entire layout of the Achaemenids.
He probably knew about the adjacent provinces and that he had to go east.
The rest can be explored during the war.

**Comment by Firesoul7** [comment]
True, but the original system you proposed sounded like Alexander wouldn't
know about any of their territory at all, when in fact he would have been
aware at least as far as Babylon. He set out on campaign with the precise
aim of making Babylon his capital.

**Comment by qweytr** [comment]
Explorers should be unlocked with ideas, just like in vanilla. Also, the initial discoveries need to reduced significantly, but not by that much. Alexander should start with most of Achaemenid Empire discovered.

**Comment by Firesoul7** [comment]
Agreed. Not every nation was making colonies, and with the changes to the
tech system nations will still have access to colonists at a decent tech
level. In addition, the ancients knew more than many think about their
surroundings. Alexander should indeed know about most of the Achaemenid
empire. I think this issue is largely closed, non?

**Comment by PhelanBavaria** [comment]
Well, if the majority votes to keep it as it is, then it's closed. Let's wait for the other 2 guys to state their opinion.

**Comment by PanzerfaustJoe** [comment]
I do agree with the province discovery needing to be reduced a bit, but otherwise just leave it as is.

**Comment by yugoslavia45** [comment]
I agree

**Comment by Firesoul7** [comment]
I do believe that's all of us.
